### ISSUE TITLE
Enhanced Course of Action Capabilities / Playbook

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#10]
Enhanced course of action capabilities includes things like automated COAs (OpenC2, others), extra impact statements, and playbook-type capabilities.

Note: this issue may be split in the future

**Work area:** https://docs.google.com/document/d/1wiG6RoNEFaE2lrblfgjpu3RTAJZOK2q0b5OxXCaCV14/edit#heading=h.uilqxp59env4

## Scope
Still being determined.

## Examples
Still being determined.

## Open Questions
Still being determined.

**Comment by jordan2175** [comment]
Additional functionality was added to working draft 04
