### ISSUE TITLE
Need ability to know where embedded relationships are located. 

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-stix2#100]
When looking at piece of content that has been marked with an object marking.  You will see: 

> "object_marking_refs": [
>   "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
>  ],

However, this assumes that you know where that marking definition object is located or that you already have it.  If you just get this object by itself, and it is marked, then you have no way of knowing if you can use it. There is no way to know where I should go to get the marking definition object that pertains to this data.  It feels like we need the ability to add a URL of where this marking definition or any other embedded relationship can be found.

**Comment by ejratl** [comment]
STIX allows for dangling references, so this is expected. This could be solved in TAXII.
