### ISSUE TITLE
Indicator / Observed Data relationship

### ISSUE THREAD

**Issue by gjGatos** [oasis-tcs/cti-stix2#102]
The Indicator object currently does not explicitly allow capturing a relationship between an Indicator and Observed Data.  This is useful to show that an Indicator was created based upon one or more Observed Data.  A separate relationship could be used to show that an Indicator identified specific Observed Data.  The first relationship is useful to show the basis of an Indicator while the latter is useful to capture metrics in whether an indicator was useful in stopping an attack.

**Comment by jordan2175** [comment]
Talked about it on the 2019-06-04 working call and decided that we would just use derived-from relationship and we should call this out out explicitly on observed-data some how.

**Comment by gjGatos** [comment]
Updated text for Indicator to state:
The common relationship “derived-from” should be used to denote that an Indicator was created based upon one or more Observed Data or other object.  For instance, an indicator may be created based upon the observation of a spearphishing email or created based upon analysis performed on a piece of malware or adversary infrastructure.

**Comment by jordan2175** [comment]
Text added to WD05
