### ISSUE TITLE
Be consistent with references to hash-algorithm-ov and -enum

### ISSUE THREAD

**Issue by clenk** [oasis-tcs/cti-stix2#103]
In 2.1 WD03, the `hashes` property of `File` references `hash-algorithm-enum`, but in Part 1 Section 7: Vocabularies, it is listed as `hash-algorithm-ov` and the "Dictionary keys MUST come from the hash-algorithm-enum" message is not repeated anywhere else the `hashes` type is used.

For reference: https://github.com/oasis-tcs/cti-stix2/issues/32#issuecomment-342472887

**Comment by ejratl** [comment]
Good catch, comment added to current working draft.

**Comment by jordan2175** [comment]
change made.
