### ISSUE TITLE
Fix `spec_version` description

### ISSUE THREAD

**Issue by clenk** [oasis-tcs/cti-stix2#106]
In 2.1 WD03, Part 1, the `spec_version` description for Language Content and Marking Definition say "Per STIX Version 2.1" but spec_version description in the Common Properties section says "Per STIX Version 2.0".

**Comment by ejratl** [comment]
I can't find this in the current version - will you validate whether this is still an open issue, please?

**Comment by clenk** [comment]
Yes, the discrepancy has been resolved in the latest draft. But the description of the property at https://docs.google.com/document/d/1ShNq4c3e1CkfANmD9O--mdZ5H0O_GLnjN28a_yrEaco/edit#heading=h.xzbicbtscatx still references the 2.0 spec:

> Per the STIX™ Version 2.0. Part 1: STIX Core Concepts (TODO REF) specification, if objects are found where this property is not present, the implicit value is 2.0.

I wasn't able to find anywhere in the 2.0 spec that said the implicit value is 2.0, so maybe that paragraph doesn't need to reference a different part of the spec; I have added a suggestion in the current draft.

**Comment by jordan2175** [comment]
spec_version the way we have it now was added in 2.1 and did not exist in 2.0.
