### ISSUE TITLE
Fix Observed Data *_observed property descriptions

### ISSUE THREAD

**Issue by clenk** [oasis-tcs/cti-stix2#109]
In 2.1 WD03, Part 2, Section 2.10: Observed Data - first_observed, last_observed, and number_observed are required, but their descriptions say "If this property is present..." If they're required, they're _always_ going to be present so this is redundant.

**Comment by ejratl** [comment]
Good catch! Suggestion added to current working draft, awaiting disposition.

**Comment by jordan2175** [comment]
change accepted.
