### ISSUE TITLE
Clarify `created` timestamp precision on marking-definition objects

### ISSUE THREAD

**Issue by clenk** [oasis-tcs/cti-stix2#111]
The `created` property on the marking-definition object doesn't have the same requirement to be to the nearest millisecond that other objects' `created` properties have, yet the pre-defined TLP instances all have `created` properties with milisecond precision, as does the example Statement marking definition. Perhaps some clarifying text could be added to the marking-definition properties table entry for `created`, e.g.:

> The created timestamp in marking-definition does not share other STIX objects' requirement to be precise to the nearest millisecond.

**Comment by jordan2175** [comment]
This was fixed in Working Draft 04.  All the common properties are now defined only once.  This was an oversight before.
