### ISSUE TITLE
Versioning of Data Markings: Missing Direction on how to associate markings with previous use of said marking

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#115]
http://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_Toc496709277

states:
>A version of a STIX Object is identified uniquely by the combination of its id and modified properties. The first version of the object MUST have the same timestamp for the created and modified properties. More recent values of the modified property indicate later versions of the object. Implementations MUST consider the version of the STIX Object with the most recent modified value to be the most recent state of the object.

But Data Markings are not addressed in the Versioning section of the Core Concepts docs. (Should have a note that Data markings are different and link to Data Markings section).

Data markings then say:

> Unlike STIX Objects, Marking Definition objects cannot be versioned because it would allow for indirect changes to the markings on a STIX Object. For example, if a Statement marking is changed from "Reuse Allowed" to "Reuse Prohibited", all STIX Objects marked with that Statement marking would effectively have an updated marking without being updated themselves. Instead, a new Statement marking with the new text should be created and the marked objects updated to point to the new marking.

What is the intended direction for handling new Stix Data Defintions/Data Markings being applied and having some sort of link to the previous iteration of that data marking? (If there is such a thing...).

Example: If a Data marking `Statement` type is updated with new text.  Should this result in a new Defintion with a new ID?  If the statement is modified, but its intent remains the same / it is the same "marking that is being applied to something even though the content might change slightly", does this mean it is a change to the ID it self?

If the above is "yes", What is the direction for reconciliation of incoming data with existing security layers?  As IDs change because of updates from outside systems, this means there is some sort of auto-magic reconciliation to occur or you are endless generating additional "checks".

edit: Additionally, what is the direction on comparison of Data Definitions/Data Markings?  With SDOs it is ID+Modified Date as per the docs.  Should Data Markings be compared using ID+Created ? (As Data Markings do not have a Modified Date property)

**Comment by rpiazza** [comment]
Hi @StephenOTT:

I'm not sure I understand your question, especially because you quote the text in the spec which explicitly prohibits versioning Data Markings.  As you posit - any change to the (statement) data marking text (even one that doesn't change the semantics) requires the creation of a new Data Marking with a new ID.  

How to handle this "change" is outside the scope of the specification, but would probably involve the "additional checks" in an implementation, which you referred to - although I'm not convinced that this processing would be onerous.

**Comment by jordan2175** [comment]
I agree with @rpiazza.  I am not sure what else we need to do.  If there is specific text we can add to help make this more clear, then I am all for that.

**Comment by StephenOTT** [comment]
I think it was more about that data markings end up being like a permanent created object. From a impl standpoint this was different from the other objects and the downstream use and life cycle management of markings come into play. It means if you need to update a marking, you are potentially having to update a huge number of other stix objects to have the new marking id.  Statement is a good example because if there was additional text added, then it's a whole new id and has rippling effects on updating N objects in the system. 

It also means that from a impl standpoint there is a super structure that defines a marking, and then it becomes versioned.  

I was pointing out that these implications are fairly significant for anyone mapping data markings to a another "thing" in their systems, and the impacts it can have when your upstream system makes a change that causes a new id on the markings to be created.  

What I see happening is in practice people are going to create x_ props that correlate to the super structure definition.

**Comment by jordan2175** [comment]
We talked about this on the 2019-06-11 working call.  Data markings are immutable. The TC has talked about this for a long time and does not have a desire to change this.  If there is text we can add to warn people or help people, please suggest it.  Please suggest some concrete text that can be used and we will look at this for 2.2.
