### ISSUE TITLE
Data Markings / Marking Definitions: These are "Security in that moment in Time"?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#116]
Data Markings do not have versioning as per the spec docs.  

So given no versioning / ability to link a changed/updated a linkage to a marking once it has been modified, does this mean that Markings should be treated as a "Security in that moment in time" ?

Another way to phrase this: A marking is the security of the object at the time that it was generated, BUT it does not maintain a link to the objects source's security object that is placed on the CTI that generated the STIX object?  Meaning that if you compared two versions of a the same SDO, the SDO might have two different TLP levels (say White and Red): but you would not be able to tell from the marking if it's the same Data Marking that has had its level updated to Red, or if there was a new Data Marking applied.

Scenario:

You have a Attack Pattern and it has a Data Marking of TLP White.  This marking is given to all Attack Patterns of a certain classification.  But then it is identified at this "certain classification" of attack patterns needs to be changed from White to Red.  in the CTI DB this is updated as a top level classification: so all attack patterns of the certain classification are automatically changed to TLP red.

But When a new STIX instance is generated for one of these attack patterns, the new instance would have a TLP Red, but the previous generation of the Attack pattern is TLP White.

So the implementation question becomes: what is your recommended way to reconcile the difference between a "new" TLP that was added, and a previous TLP that was updated from white to red.  

The best i could determine was that a custom field needs to be created that would have some level of tracking in the same way that SDOs can use the ID + modified date to track versioning.  

Thanks!

**Comment by clenk** [comment]
I believe you would just update the `object_marking_refs` property on the SDO to point to the TLP Red marking definition object instead of the TLP white marking definition object. I don't think marking definition objects are meant to be modified.

> but you would not be able to tell from the marking if it's the same Data Marking that has had its level updated to Red, or if there was a new Data Marking applied.

You would be able to tell which data marking is applied by the ID in the `object_marking_refs` property.

**Comment by StephenOTT** [comment]
@clenk the `object_marking_refs` would be a value of the "current state".  When a marking is updated (from white to red), it would seem to be a "value" and not a business categorization.  Meaning that If the `"Sensitive Data Level 123ABC" classification` is updated from being white, to red. The SDO only knows that its now "red", it does not know that the `"Sensitive Data Level 123ABC" classification` has changed, because there does not appear to be a way to link/group data markings that have changed.

Lets use a more json real example:

```json
    {
      "type": "attack-pattern",
      "id": "attack-pattern--083048b9-444b-4653-ba26-b9c3d99fccf6",
      "created": "2018-11-26T01:48:47.794Z",
      "modified": "2018-11-29T01:48:47.794Z",
      "revoked": false,
      "object_marking_refs": [
        "marking-definition--bd5cccb0-72a1-4297-b804-74cb2eb7b5b2"
      ]
...
}
```

and 

```
    {
      "type": "marking-definition",
      "id": "marking-definition--bd5cccb0-72a1-4297-b804-74cb2eb7b5b2",
      "created": "2018-11-26T01:48:47.833Z",
      "object_marking_refs": [
        "marking-definition--768e0df9-d4ea-4744-a3e3-641dfdd1e1dd"
      ],
      "definition_type": "tlp",
      "definition": {
        "tlp": "white"
      }
    }
```

So the discrepancy i see is does a marking definition(MD) represent a single snapshot related to teh attack pattern, or would you see that specific marking definition ID be applied to many SDOs in many different bundles over time?  For example this MD might be applied today, and then next week, and in 2 months from now.  All with the same ID and same definition details.  If you were to generate the same Attack Pattern STIX SDO 5 times, would each of the 5 have the exact same Object Marking Refs UUID mapping? (The definition content might be the same, but the actual UUID might be different, thus making them snapshots in time)
 (If the above is not what occurs, and a MD is just a single snapshot in time, then let me know and the below i think can be ignored).

Then one day, 

the MD has this change occur:

```
      "definition": {
        "tlp": "red"
      }
```

According to the spec, this would generate a new ID for the MD, as there is no versioning.

Depending on the down stream consumers and how the data is absorbed into the CTI DB, there seems to be a implementation detail / note to address around usage:

If our MD was applied to all SDOs that have a specific classification, then the consumer would have to question: do i just update the single SDO with the new marking or do i update all previous SDOs with the same marking to the new classification level (white to red)?

From a implementation level, it appears this way a bit because of the First-class treatment that marking-definitions are given in a bundle.

**Comment by clenk** [comment]
@StephenOTT I would assume you would use a single "canonical" instance of a given MD that all the SDOs would use. You wouldn't need to regenerate a marking definition if you already have one with the type and value you need, just reuse that ID. But maybe it depends on your implementation.

The "snapshot" aspect is the SDO with a specific `modified` property and specific ID(s) in the `object_marking_refs` and/or `granular_markings` properties, not the Marking Definition itself.

**Comment by jordan2175** [comment]
Marking definitions is by design a definition that is applied to an object a certain point in time for a certain version of the object.  The TC did not want to allow marking definitions to be versioned, since there would be no way to guarantee that the end user / consumer got the updated marking definition.  Further, you would have to track not only which marking definition you were using, but also the version of it.  And that tuple is just overly problematic. If you want to change an indicator from TLP:GREEN to TLP:RED you need to release a new indicator that points to the TLP:RED data marking.  If you no longer want the old one floating around, you should first revoke the old indicator and then create an entirely new indicator. At some point it would be good if someone in the TC wrote a best practices guide for dealing with data markings.
