### ISSUE TITLE
it is assumed that a bundle's objects will have all referencing data?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#117]
it is assumed that a bundle's objects will have all referencing data?

Is it assumed and expected that a bundle will have all of the objects needed for all references/relationships in the objects of the bundle?

Example if a Bundle has a Attack Pattern with a specific `related-to` a another SDO.  Is it required tha the bundle have the second SDO as a object?  Is it possible for objects to have references to other objects that are not included in the bundle?

**Comment by jordan2175** [comment]
No, you should never assume that the bundle will have all of the relevant data.

**Comment by StephenOTT** [comment]
okay great.
Thanks
