### ISSUE TITLE
Historical reasons for references to be list of IDs rather than list of Objects with Type and ID

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#118]
Hi

as I have been working through the spec and working through serialization and deserialization implementation scenarios, wanted to understand the historical reason for having any references/relationships (anything that is a reference to another bundleable object) is stored as a ID or list of IDs.  What was the thinking for why it was not a Object with `type` and `id` or a list of objects with the `type` and `id` ?

I ask this because I find there is a inconsistency in the providing of Types from a implementation level: were the `type` field is always provided allowed a implementation to detect the Type.  But this is thrown out the window when dealing with any relation to other bundleable objects. (SDO, SRO, Marking Definitions), where these need to be specially introspected to evaluate the ID, parse it, and determine the "type".

Thanks!

**Comment by StephenOTT** [comment]
Something like:

```
{
  "relationship_type": "derived-from",
  "source_ref": "attack-pattern--337e6c28-17dc-4416-8732-31a9913c75ce",
  "target_ref": "attack-pattern--5a94b6b5-8b9d-439b-9779-839ad48b2146",
  "type": "relationship",
  "id": "relationship--fd5d721c-c256-4102-9046-b97cf2be6a86",
  "created": "2018-12-07T15:52:13.348Z",
  "string": null,
  "modified": "2018-12-07T15:52:13.349Z",
  "revoked": false
}
```

vs


```
{
  "relationship_type": "derived-from",
  "source_ref": {
    "type": "attack-pattern",
    "id": "attack-pattern--337e6c28-17dc-4416-8732-31a9913c75ce"
  },
  "target_ref":  {
    "type": "attack-pattern",
    "id": "attack-pattern--5a94b6b5-8b9d-439b-9779-839ad48b2146",
  },
  "type": "relationship",
  "id": "relationship--fd5d721c-c256-4102-9046-b97cf2be6a86",
  "created": "2018-12-07T15:52:13.348Z",
  "string": null,
  "modified": "2018-12-07T15:52:13.349Z",
  "revoked": false
}
```

**Comment by jmgnc** [comment]
It's this way because we use the same convention for the id property.  Why didn't you suggest breaking out the id property the same way?   Having two different ways to represent the same data is BAD.

**Comment by StephenOTT** [comment]
👌
