### ISSUE TITLE
Anywhere that has reference to regex-able constraints, should have the regex provided in the docs

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#119]
Throughout the docs there are lots of places where there are reference to regexable rules such as 

>Keys MUST be unique in each hashes property, MUST be in ASCII, and are limited to the characters a-z (lowercase ASCII), A-Z (uppercase ASCII), numerals 0-9, hyphen (-), and underscore (_). Keys SHOULD be no longer than 30 ASCII characters in length, MUST have a minimum length of 3 ASCII characters, MUST be no longer than 256 ASCII characters in length.

anywhere there is a constraint that STIX docs can provide a pre-build regex that is for the constraint, this would be great for implementers!

**Comment by jordan2175** [comment]
Please feel to provide them

**Comment by jordan2175** [comment]
An example called out in #126  
Provide a Regex for allowed Granular Expression operator usage.

**Comment by rpiazza** [comment]
These might be available in the json schemas or stix-validator (see https://github.com/oasis-open)

**Comment by jordan2175** [comment]
If these can be provided, the editors could add them in

**Comment by clenk** [comment]
The validator and schemas are supposed to be non-normative, and we've had to update the regexes they use several times as people found bugs with them. I wonder if a Committee Note might be a better place for them since I assume it would be easier to update than the spec itself?

**Comment by jordan2175** [comment]
@clenk you are correct and that is a great point.  I will be closing this issue because of that.  I do think that a committee note might be a great option for these sorts of things.
