### ISSUE TITLE
Hashing Algo Vocab vs other Vocabs: use of "x_" naming ?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#120]
Hi

noticing that the 
http://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_Toc496709264 states the following:

>The Hashes type represents 1 or more cryptographic hashes, as a special set of key/value pairs. Accordingly, the name of each hashing algorithm MUST be specified as a key in the dictionary and MUST identify the name of the hashing algorithm used to generate the corresponding value. This name SHOULD either be one of the values defined in the hash-algorithm-ov OR a custom value prepended with “x_” (e.g., “x_custom_hash”).

Specifically the last part of `OR a custom value prepended with “x_” (e.g., “x_custom_hash”).`.

Why does hashing algo vocab implement a additional rule for the names of a vocab, but the other open vocabs do not seem to implement this rule? (seems like a pretty good rule actually...)

Example AttackMotivations vocab allow additional items to be added but does not seem to have direction around the naming.

Generally would be pretty good if there was a general rule that additional vocab items were to use the "x_*" pattern.  This makes implementation very easy to support additional properties and still enforce the core OVs.

**Comment by jordan2175** [comment]
We should remove this from the hashing rule.  Vocabs should not have this rule.

**Comment by jordan2175** [comment]
removed text based on consensus from today's working call
