### ISSUE TITLE
Custom Objects: Bundle: Goes in objects prop or "custom_objects" prop?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#121]
as per http://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_Toc496709311

The Custom objects section shows a new property called "custom_objects":

```
{
  "type": "bundle",
  "id": "bundle--f37aa79d-f5f5-4af7-874b-734d32c08c10",
  "spec_version": "2.0",
  "custom_objects": [
    {
      "type": "x-example-com-customobject",
      "id": "x-example-com-customobject--4527e5de-8572-446a-a57a-706f15467461",
      "created": "2016-08-01T00:00:00.000Z",
      "modified": "2016-08-01T00:00:00.000Z",
      "some_custom_stuff": 14,
      "other_custom_stuff": "hello"
    }
  ]
}​
```

but this property is not documented or mentioned anywhere in the Stix Objects or Core Concepts docs.

Do custom objects go into a "custom_objects" array as per the example provided?  If yes, can you provide some background for the reasoning for this?

**Comment by clenk** [comment]
This is a duplicate of #91. However, I believe both of these issues have been fixed in the latest STIX 2.1, as per the changelog:

> In Part 1, §8.2.1, fixed an example of the Bundle object that had an incorrect key name.

**Comment by StephenOTT** [comment]
@clenk  the fix was to add custom objects into the "objects" property?

**Comment by StephenOTT** [comment]
@clenk thank you!

**Comment by jordan2175** [comment]
This was fixed back in WD01
