### ISSUE TITLE
Property/key length inconsistency ?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#122]
Custom Properties have a key length limit of 250.

But Hashes have a key length limit of 256.

is this on purpose?  What is the reasoning for this?

Thanks!

**Comment by jordan2175** [comment]
We have done this every where in the documents, but we missed this one value.  So I suggest that we change it to be consistent.

**Comment by jordan2175** [comment]
The editors talked about this, and have made the change to make it the same as everywhere else.  This was just missed in the last round of cleanup.
