### ISSUE TITLE
Discrepency: region-ov and Location examples 

### ISSUE THREAD

**Issue by clenk** [oasis-tcs/cti-stix2#124]
In STIX 2.1 WD03, Part 2, Section 2.7 Location, the first example has `"region": "north-america"`. However in the Vocabulary section in Part 1 of the spec, there is `northern-america` but not `north-america`. This is an open vocabulary so it is still valid STIX, but was the intent to use the value from the vocabulary?

**Comment by ejratl** [comment]
Great catch! Suggestion & comment added to the current working draft.

**Comment by jordan2175** [comment]
Change accepted.
