### ISSUE TITLE
Granular Markings: Consider that Selectors are a Array of Objects

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#125]
When working with Selectors for granular markings, there is a use case where you want to define redaction configurations on a per selector basis.  So that you can define which selectors are for field removal, vs field modification with a new value.  This does not seem to be possible at the moment, and you would have to apply multiple granular markings with duplication Marking Refs.

**Comment by ejratl** [comment]
Can you provide an example that clarifies exactly what you would like to do, please?

**Comment by srrelitz2** [comment]
Only creator of Object can modify object.  Redaction of object is prohibited by Spec.
