### ISSUE TITLE
Change the integer definition to be a 54-bit number per RFC 7493

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-stix2#128]
Right now in STIX we have defined the Integer value to be a 64-bit value, however, due to interoperability issues the IETF defined I-JSON (internet JSON RFC 7493) that says an Integer must be a 54 bit number between the range of  ([-(2**53)+1, (2**53)-1]).  Since the ECMA standards / JavaScript standards also require this and most JSON parsers also require this, it would be best for us to put this restriction in place and follow the industry best practice.   This will ensure that STIX data can be used with off the shelf JavaScript and other program language libraries for handling JSON.

It is important to note that we got this right for the Float definition in STIX, we just got it wrong for the Integer definition.  Meaning, the Float definition is already RFC 7493 compliant.

**Comment by StephenOTT** [comment]
@jordan2175 where in the spec does it dictate a 64bit value for integer?  I am looking at COO core concepts for example, and it only states that it is a "whole number"

**Comment by varnerac** [comment]
We reference [RFC-7159](https://tools.ietf.org/html/rfc7159#section-6) which recommends keeping numbers within IEEE754 binary64. This refines that.

**Comment by StephenOTT** [comment]
7159 is discussed in STIX Core Concepts. But it's not mentioned in the same way for cyber observables core concepts.  Recommend you add the same info or remove the duplicate code concepts in COO and refer the reader back to STIX objects Core Concepts.

**Comment by jordan2175** [comment]
This change was finalized a few weeks on a working call.
