### ISSUE TITLE
Add normative requirement for timestamp order in first_*, last_*

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#13]
Per CSDPR02#7 (https://docs.google.com/spreadsheets/d/1YOPONeKzc6Uu1A1MS3WkICG26LKLQOWdr-KBDzM8K6Y/edit#gid=5055878), any time there's a first_* timestamp and a last_* timestamp, we should add a normative requirement saying that the first_ timestamp MUST be before the last_ timestamp.

**Comment by skelley1** [comment]
This was discussed in October 2017, and the TC agreed that this should be the case.

**Comment by johnwunder** [comment]
This was implemented in the specification, closing.
