### ISSUE TITLE
Marking definition really needs a modified timestamp for TAXII

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-stix2#130]
There is a problem with our `Marking Definition` object and TAXII.  TAXII needs the ability on the `status` resource to tell the client which version of the object was added, failed, or is pending.  The problem is that the `marking definition` object does not have a `modified` timestamp.  I understand all of the reasons WHY we did not want to allow marking definitions to be updated and I am NOT suggesting that we change that view.  What I am suggesting is that we add the `modified` timestamp to the `marking definition` and just say that it MUST equal the `created` timestamp and it MUST NOT be versioned / updated.

**Comment by StephenOTT** [comment]
@jordan2175 I dealt with this same issue on the taxii-springboot side... is this not more of a implementation issue and less spec?  As in the implementation may implement a 3rd column/timestamp which is either the modified or created timestamp depending on the Bundleable object.

**Comment by ejratl** [comment]
Comment added to current working document to spur discussion towards resolution of this issue.

**Comment by jordan2175** [comment]
We talked about this on the 2019-06-11 working and we are rejecting this. This is a product and code problem.
