### ISSUE TITLE
Distinguish Custom SDOs vs SROs

### ISSUE THREAD

**Issue by varnerac** [oasis-tcs/cti-stix2#131]
This is a breaking change.

Currently we do not have a way to distinguish custom STIX Data Objects from STIX Relationship Objects (SROs). STIX 2.1 SROs have three required fields, `relationship-type`, `source-ref`, and `target-ref`.

We should be able to discern if a Customer STIX Object is an SDO or SRO.

I propose adding the following test, perhaps to Part 2, Section 2 "STIX Domain Objects".

> STIX Data Objects MUST NOT have the properties  `relationship-type`, `source-ref`, or `target-ref`. These properties are reserved for STIX Relationship Objects.

**Comment by StephenOTT** [comment]
@varnerac I was dealing with this issue a few days ago with STIX-Java lib and I was coming to the conclusion that its more of a implementation detail with type requirements at the property level.

Is there a specific field/prop that is ambiguous where the context of the specific property that you are interacting with could be a SDO or SRO?
Even with custom objects, you would have a "type" field which is your implementation mapping marker to the implementation's code around that specific custom sdo or custom sro.

**Comment by varnerac** [comment]
So, my proposed text is wrong. I think the answer is that we do not have a way to distinguish custom SDOs from custom SROs. However, I am not sure that it matters. We have two SROs, `relationship` and `sighting`. If I were to create a custom SRO that the system didn't know about, there'd be know way to handle it. However, I am now not sure there is a scenario where it matters if the custom object I am storing is an SDO or an SRO.

**Comment by StephenOTT** [comment]
Based on that description, I would then suggest a better spec requirement would be that no obejcts share the name type value. As in a SDO type value cannot be the same as a SRO type value.  When a custom object is parsed by a library, you would know the supported "type" values and be able to determine proper parsing context.  If a custom implementation needed to support dynamic custom objects that are determine at runtime, then that would seem a prime use case for x_ properties on the object. Such as `x_stix_type : sro`

**Comment by jordan2175** [comment]
Yeah, we do not really have a way yet to say that something is an edge versus a node.

**Comment by jordan2175** [comment]
We talked about this on 2020-02-11.  The consensus on the call is not do anything here.  Drew might look at this later and see if he can figure out some other proposed text if any.
