### ISSUE TITLE
Message ID field in email message object

### ISSUE THREAD

**Issue by skelley1** [oasis-tcs/cti-stix2#132]
We  should add a property for message-ID to the email object. According to RFC 2822, "The "Message-ID:" field contains a single unique message identifier."

This seems like it would be useful for specifically identifying one email, as opposed to others.

**Comment by ejratl** [comment]
Added as a suggestion to the current working draft. This property can be captured in additional_header_fields property so elevating it to the top level depends on how people want to use the object.

**Comment by jordan2175** [comment]
The editors have accepted this change.
