### ISSUE TITLE
Relax requirements for UUID to allow time-based generated ones

### ISSUE THREAD

**Issue by adulau** [oasis-tcs/cti-stix2#133]
The current STIX Core Concept document states that UUID MUST be only UUID version 4:

~~~~
The UUID  MUST be generated according to  the algorithm(s) defined in RFC 4122, section 4.4 (Version 4 UUID) 
~~~~

As discussed in Slack and other channels, some STIX documents with UUIDs are generated with other algorithms which is basically limiting current threat intelligence platform to import STIX documents due to the strictness of the standard (cf. https://github.com/oasis-open/cti-python-stix2/pull/235). 

We ask to change the specification to relax the UUID format and mention that Version 4 of the UUID is only RECOMMENDED.

**Comment by jordan2175** [comment]
This was done for working draft 04.
