### ISSUE TITLE
Cyber Observable: Archive File Extension missing "minimum 1" requirement?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#134]
For the Archive File Extension it states that the field `contains_refs ` is required, but it does not state if there must be a minimum of 1 object in the array.  Is this a mistake or can it be a empty array?

http://docs.oasis-open.org/cti/stix/v2.0/cs01/part4-cyber-observable-objects/stix-v2.0-cs01-part4-cyber-observable-objects.html#_Toc496716234

**Comment by ejratl** [comment]
The linked text says "..as a reference to **one or more** other File Objects..." (emphasis added), so I'm struggling to understand where you want the restriction applied. Do you require the limitation to be added to the MUST statement or is it sufficient to have it in the description?

**Comment by StephenOTT** [comment]
Where do you see that in the link above?  Can you provide a screenshot?

**Comment by ejratl** [comment]
<img width="1110" alt="Screen Shot 2019-04-05 at 5 04 19 PM" src="https://user-images.githubusercontent.com/1165700/55658898-f0670280-57c4-11e9-9e18-23c668f62b4a.png">
In the table, under Description for the contains_refs field the first sentence "Specifies the files contained in the archive, as a reference to one or more other File Objects." with the emphasized part "one or more". Are you seeing the same?

**Comment by StephenOTT** [comment]
🤕  so agreed its there.  I must have read it 5 times and brain did not see it.  I would suggest that the style of sentence is prone to mistakes: Its easily missed when skimming for the requirements.

Having some more clear language for use when its a List would be greatly appreciated.

**Comment by jordan2175** [comment]
We should clean up the language to make it more clear

**Comment by jordan2175** [comment]
we rewrote this text to say:

"This property specifies the files that are contained in the archive. It MUST contain one or more references to a File objects."
