### ISSUE TITLE
Reasoning for distinction between Vocabs and Enums?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#135]
In Cyber Observable Objects there are several usages of "Enums" such as `​2.12.4.2​ ​Network Socket Address Family Enumeration`.  What is the reasoning for treating these are `enums` rather than as `vocabulary` pattern used in SDOs, SROs, etc?

**Comment by StephenOTT** [comment]
exact type of confusion shown in #103

**Comment by ejratl** [comment]
The current working draft contains the following explanation: 

> STIX vocabularies that have type names ending in '-ov', are "open": they provide a listing of common and industry accepted terms as a guide to the user but do not limit the user to that defined list. These vocabularies are referenced from the STIX Objects as type open-vocab and have a statement indicating which vocabulary should be used.
> 
> STIX vocabularies that have type names ending in '-enum' are "closed": the only valid values are those in the vocabulary. These vocabularies are referenced from the STIX Objects as type enum and have a statement indicating which enumeration must be used.

**Comment by StephenOTT** [comment]
What is the justification for having closed enums/vocabularies?  It's a spec designed for trust groups to implement. So would it be prudent to have all lists to be "open" to allow the final impl to control the allowance or denial of additional values ?

**Comment by jordan2175** [comment]
In STIX 2 we wanted to open up the vocabularies to until such a time as we felt that they were solid.  So most all vocabularies start as open vocabularies.  Then over time, maybe years, they will eventually get locked down to be a closed vocabulary or enum.  The whole purpose of STIX is to enable machine readable content.  The more standardized it is, the more likely machines will be able to process the content in real-time.  But this will take time to get there.  The hope is that the vocabs that we know and understand really well over time will get locked down. But until that time, they are open so the industry can tell us what we are missing and what needs to be added. But some vocabs we already know really well and there is no wiggle room.  So those are defined as an enum.
