### ISSUE TITLE
Cyber Observables: Email Message: additional_header_fields is Dictionary, but Dictionaries do not support duplicate fields and Email headers can have duplicate entries

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#138]
Cyber Observables: 

Email Message: 

`additional_header_fields` is type `Dictionary`, but Dictionaries do not support duplicate fields and Email headers can have duplicate entries/duplicate keys

**Comment by StephenOTT** [comment]
Also note that the specific def of email message headers addresses the issue with:

`For cases where a header field occurs more than once, the corresponding value for the dictionary key MUST be a list of type string, where each string in the list represents a single value of the header field.`

But this is a larger issue of the construct of "Dictionary" usage.  We now have Dictionaries with "exception" definitions.  The Construct of Dictionary needs to be resolve as its a overly complex data model that is increasingly problematic

**Comment by jordan2175** [comment]
Based on working call on 2019-05-28 we changed the text to say: "The value MUST always be a list of type string to support when a header field is repeated. "

**Comment by jmgnc** [comment]
see: https://github.com/oasis-tcs/cti-stix2/issues/137#issuecomment-496696212
