### ISSUE TITLE
At least one property should be required in windows-pe-optional-header-type

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#14]
In part 4, section 2.7.6.3: all properties of windows-pe-optional-header-type are optional.  We should add a normative statement that says at least one property should be populated.

https://lists.oasis-open.org/archives/cti-comment/201705/msg00005.html

**Comment by jordan2175** [comment]
Added the following suggested text to 6.7.6.2

"An object using the Windows PE Optional Header Type MUST contain at least one property from this type."

**Comment by jordan2175** [comment]
This change and Ivan's change were accepted.
