### ISSUE TITLE
Process COO: arguments property is defined as list but does not have spec to if duplicate values are supported

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#140]
The Process COO has a `arguments` prop but is missing context to if duplicate values are supported.

IMO, duplicates should be supported.  In most other cases in the spec for COO and other Stix related objects, duplicates should not be supported as they do not make sense in the context.  But for arguments, duplicate arguments could be a vector to cause a malicious action on a application.  

The spec should have text that "SHOULD" support duplicate values in the List.

**Comment by ikiril01** [comment]
I believe we deprecated `arguments` in STIX 2.1 CSD01, so the only way to capture command-line arguments is through the `command_line` property (a string).

**Comment by ejratl** [comment]
Closing based on ikiril01's comment.

**Comment by StephenOTT** [comment]
Before closing issues can we confirm that it was actually fixed with a ref to the fix.

**Comment by ejratl** [comment]
You can validate that arguments is no longer in the object definition in the latest publicly posted working draft here: https://www.oasis-open.org/committees/document.php?document_id=63875&wg_abbrev=cti%20 I don't think that it helps anybody to leave this issue open until the next version of the spec is released.
