### ISSUE TITLE
X509 Certificate COO has a explicit x509_v3_extensions property rather than using the COO generic "extensions" property: why is this?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#141]
X509 Certificate COO has a explicit x509_v3_extensions property rather than using the COO generic "extensions" property: why is this?

**Comment by ikiril01** [comment]
I believe the rationale here was that although x509 v3 extensions are "extensions" to the default x509 property set, they are utilized commonly enough and valid for base x509 use cases that it didn't warrant creating a COO extension (which is really meant to address use cases outside of the base).

**Comment by rpiazza** [comment]
Additionally, they are an extension to X509 spec, not the STIX 2.x X509 object spec.  
It is an unfortunate use of the same word to mean two similar but different things.

**Comment by StephenOTT** [comment]
It's a very confusing overlap of terminology.  Especially at the code level.

**Comment by rpiazza** [comment]
Agreed - I had the same confusion when I first saw it.

**Comment by jordan2175** [comment]
We rewrote the text to say:

"Note that the use of the term "extensions" in this context refers to the X.509 v3 Extensions type and is not a STIX Cyber Observables extension. Therefore, it is a type that describes X.509 extensions."
