### ISSUE TITLE
Cyber Observables should not implement lists that require array order to be maintained

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#142]
There are several Cyber Observables that have spec requirements that the Array's maintain order.

This is a really risky for this data...  Order can be lost at any point (serialization, deserialization, DB storage, DB Query response, performing any sort of sort, transmission, etc. (and yes it is understood that JS spec says that array order should be maintained, but spec is not the reality)

**Is there a specific reason why these lists were not implemented as a proper object with an `Order` and `Value` property?**

Noticed so far:

1. Network Traffic: `protocols`
1. Email Message: `received_lines`

**Comment by jmgnc** [comment]
Yes, because Lists in STIX are required to be ordered.  It is up to the implementor to do the conversion internally if their implementation of List does not maintain order.

This is required by 2.0, so, changing it now is a little bit late, and will make a backwards breaking change.

**Comment by StephenOTT** [comment]
in the areas where data sort actually matters, the use cases are pretty damn important to safe guard against order loss. Given that this is a spec for data interop and data transfer, it's a large gap in data integrity assurance. Would take the smallest of errors to lose the sort without any indicator.

**Comment by varnerac** [comment]
I’m unclear how the RFC8259 requirement that JSON arrays are ordered isn’t enough. How would moving from a JSON array, an ordered data type, to a maps with an `order` key help?

**Comment by StephenOTT** [comment]
Because ordered arrays are rarely respected in the spec and when moving out of Json and you parse objects into other languages it is so easy for this to be missed. Just because there is a spec does not mean it's followed. Look at the http rest spec for continual proof of this   Saying "the spec protects us" does not mean it gets implemented like this, or the subsequent DBs, and other formats will conform.

**Comment by varnerac** [comment]
If people don’t follow the spec, that’s on them. The JSON and STIX2 specs indicate that the data types are ordered. I see no reason to bolt ordering onto the JSON object type. It’s kludgy.

**Comment by StephenOTT** [comment]
Well we know have a double sided issue:  we have arrays that have ordering without the need for order (such as labels) and we have arrays with ordering that are sensitive to the slightest error in data change. 

The exact solution is being proposed. But it is a very large "trust the implementer" you are creating for data that has very little indicators of error/miss-Sort

**Comment by ejratl** [comment]
@StephenOTT I propose closing this issue based on the discussion.

**Comment by jordan2175** [comment]
The best place to address this is in the interop specs.  We can make this a test that people would have to assert that they are complaint with, before they can get the STIX Preferred certification.  JSON arrays/lists are ordered by definition.  So all lists / arrays in STIX2 are ordered.  Yes, for some it does not matter the order, but that is okay that they are ordered.  It does not hurt anything having them be ordered.  Another key design goal of STIX2 is simplicity.  STIX 1.x had verbose complexity and optionality, and that is why it failed. We have learned from those mistakes and trying to add a special type of property to allow for defining if a list is ordered or not would be overly complex and provide very little value.
