### ISSUE TITLE
Windows Registry datatype enumeration

### ISSUE THREAD

**Issue by coreybfoulds** [oasis-tcs/cti-stix2#143]
I am working on an integration for a service called GRR rapid response on a project that uses stix cyber observable as our data model. 

I noticed that the Registry datatype Enumeration does not include the  REG_DWORD_LITTLE_ENDIAN type. I am aware that windows is built on little endian so is is refered to as just dword, but in the GRR api data that is returned they explicitly use  REG_DWORD_LITTLE_ENDIAN. I also see that Windows defines this as well. Here: https://msdn.microsoft.com/en-us/library/windows/desktop/bb773476(v=vs.85).aspx

Would it be possible to add this enum?

**Comment by ikiril01** [comment]
This makes good sense - I don't see any reason not to add this to the enum.

**Comment by jordan2175** [comment]
I think this is reasonable to add.

**Comment by jordan2175** [comment]
Change accepted.

**Comment by coreybfoulds** [comment]
Awesome! Thank you very much! :)
