### ISSUE TITLE
REPEATS is too exact

### ISSUE THREAD

**Issue by jmgnc** [oasis-tcs/cti-stix2#146]
I just realized that we may have a minor issue w/ the text for REPEATS..  it says exactly x times instead of at least x times.  This means if you say REPEATS 5 TIMES, and there is a 6th instance that should match, a very language lawyer would say that it isn't exactly 5 times anymore, and fail to match.

I propose to change the word exact to at least.

**Comment by jordan2175** [comment]
I think you might need to support both use cases.  Sometimes you might actually want an exact number, no more, no less.

**Comment by ikiril01** [comment]
What if you do want an exact number of repetition (e.g., 5 times) though? Wouldn't "at least" break the ability to specify that?

**Comment by jmgnc** [comment]
@jordan2175 Yeah, I agree that we should support both, see below for proposal.  I always envisioned that REPEATS was at least, and there wasn't an exact match.

@ikiril01 The issue is that this is hard to capture in JUST the REPEATS keyword.  As the REPEATS does not have any concept of time.  If we made it exact, then in pretty much all cases, you would have to return false, as there is almost ALWAYS be a match outside.   Though that argues that REPEATS w/o a time frame is equally less useful.

Talking w/ void, he does agree that REPEATS w/o a temporal clause doesn't make much sense.

Should we add an EXACTLY key word? so [ a ] REPEATS EXACTLY 5 TIMES to represent when it means that many times.

Though, this makes things a bit more complicated, because before, it was a simple in to out.  did I match something, yes, I did, pass it to the next qualifier.  Now there needs to be an outward in component to matches, which makes writing a matcher more complicated.  That is restrict the time frame, and then try to match.

This also gets complicated if you do an exact 5 matches, within a time frame, say 60 seconds, and there is a 60 seconds bounds that has exactly 5 matches, and another 60 second bounds that includes a 6th that would make it false.  Keeping the at least, keeps this logic simple.

**Comment by JasonKeirstead** [comment]
Both version ("at least" and "exactly") are important, however the "at least" is the most important as it's what's used in the SIEM world in nearly all rule test scenarios.

**Comment by JasonKeirstead** [comment]
My own proposal

- Add clarifiying text to existing REPEATS stating it is "at least"

- Add a new github issue to track the "exactly" gap, which may or may not be a 2.1 priority.

**Comment by jmgnc** [comment]
I agree w/ @JasonKeirstead 's proposal and support it.

**Comment by jordan2175** [comment]
Please add the text in to the document as a suggestion and tag the suggestion with this github number.  Thanks

**Comment by jmgnc** [comment]
I've changed exactly to at least.  I'm not sure if we want to add additional clarifying text on why we made that change or not.

**Comment by jordan2175** [comment]
Change was accepted on 2019-07-08 patterning call.
