### ISSUE TITLE
Timestamp Sub-Second Precision: Optional Digital counts

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#148]
Stemming from the conversations in: https://lists.oasis-open.org/archives/cti-users/201904/msg00007.html

I am raising the question to why there is optional Sub-second precision for timestamps.

More specifically why the spec says the following:

http://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_Toc496709271

>The timestamp property MUST be a valid RFC 3339-formatted timestamp [RFC3339] using the format YYYY-MM-DDTHH:mm:ss[.s+]Z where the “s+” represents 1 or more sub-second values. The brackets denote that sub-second precision is optional, and that if no digits are provided, the decimal place MUST NOT be present.
The timestamp MUST be represented in the UTC timezone and MUST use the “Z” designation to indicate this.

Based on the discussions in the email chain, the concern is about **loosing** precision:

>  "So *not* .133Z becomes .1Z. That would be a loss of precision and should *not* occur."

So given that this is the concern, I am asking why is there option on the number of digits supported for sub-second precision?  The initial answer from the email chain was: it was due to some systems being unable to create that level of precision: but If we are accepting that `.1Z` == `.100Z`, and that `.000Z` is the same as putting no digits for the sub-second precision, then have 3 digits of precision is a formatter, and the source system must match the format.  If the system is only capable of `.1Z` then it would format that as `.100Z`.

BUT i am asking the above under the initial assumption that we dont need to actually track what the source systems actual precision was.  If this assumption is incorrect, please provide some specific context to why.

**Comment by jmgnc** [comment]
The number is to allow a system to convey the precision of their time source.  If their precision is only seconds, then no sub-second digits are provided.  If they support microsecond precision, then they provide 6 digits of sub-second precision.

This is the standard way significant figures is used:  https://en.wikipedia.org/wiki/Significant_figures

**Comment by StephenOTT** [comment]
Another variation to consider


If a producer generates a .000000000Z timestamp. Should the parser keep the 9 zeros?  Or would be converted to just no zeros ?

**Comment by StephenOTT** [comment]
Think this is a good example of a reason for having a minimum sub second precision such as .000Z

**Comment by jmgnc** [comment]
> Another variation to consider
> 
> If a producer generates a .000000000Z timestamp. Should the parser keep the 9 zeros? Or would be converted to just no zeros ?

What do you mean by "keep"?  If you mean if the consumer/taxii server sends it on, does it need to send it with the 9 zeros, then yes, it needs to keep it.

If you mean convert it to floating point for internal comparisons, then no, unless you decide to do a fancy comparison algorithm where 5.234Z will compare equal to 5.2342384Z due to the lack of precision on the first one, as rounding/truncating the precision of the second one will result in a value equal to the first one.

In a few cases, objects do have a minimum/mandatory sub second precision.

**Comment by ejratl** [comment]
@StephenOTT Do you have follow-up questions? Can we close this issue?

**Comment by StephenOTT** [comment]
I think the docs should be updated with explicit explanation of the implications of the optional sub second precision and that storage of the actual digit count is required rather than just the non trailing zeros that is the impl of 99% of general date handling libs out there

**Comment by varnerac** [comment]
Does anyone know of a JSON parser that stores the trailing `0`s? I don’t. It gets converted to a number in whatever language I’m using.

**Comment by jordan2175** [comment]
The timestamps used for versioning require mili-second precision.  Other timestamps are other timestamps.  Some systems may be able to generate microsecond precision, and others may only be able to generate second level precision.  I think what you are asking for really needs to be done in a users / implementers guide.  Feel free to write up a committee note on the topic and submit it to the TC for publication.  The TC has a long and very drawn out history with debating timestamps and timestamp precision.  Literally 10s of thousands of slack messages and hundreds of emails and phone calls.  In hind sight we might have done things differently, but it is what it is at this point. I do not feel like the TC has any desire to address this again.  If you feel passionate about this, please submit some suggested text to the list.
