### ISSUE TITLE
Expand COA vocabulary

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-stix2#157]
The following entries were pulled from working draft 04 since they felt a little rushed and a little out of place.  I think we added them originally as place holders to see what they would be like.  We can add these back in for Working Draft 05. 

ietf:cacao:json | IETF CACAO standard JSON version
oasis:openc2:json | OASIS OpenC2 standard JSON version
cisco:ios:text/plain | Cisco IOS proprietary command language
microsoft:powershell | Powershell commands
sh:text/plain | Bourne Shell compatible commands
symantec:sgos:text/plain | Symantec’s proprietary course of action language

**Comment by JasonKeirstead** [comment]
Shoudn't these vocab entries have versions? There are many versions of IOS with different commands available, as an example. I think having these not tied to some kind of versioning scheme is going to be problematic when it comes to compatibility.

**Comment by rpiazza** [comment]
Bret and I were confused about this.  Bret made some changes to the text.  I think the **os_execution_envs** property was supposed to cover this - but with the changes, it may no longer.

**Comment by jordan2175** [comment]
Based on working call consensus we are moving this to a future version of STIX.

**Comment by jordan2175** [comment]
Since COA was reverted back to 2.0 and thus any future design for COA will probably be different, this issue is being closed.
