### ISSUE TITLE
Sightings SRO: observed_data_refs objects must have first_observed and last_observed within the Sighting's first_seen, last_seen limits?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#159]
A Sighting has a first_seen and last_seen time range.

The ObservedData objects that are applied in the Sighting's observed_data_refs also have first_observed and last_observed.

Are the Observed Data subject to the Sightings time frame?

**Comment by StephenOTT** [comment]
Clarification contexts:

Look at Sighting: http://docs.oasis-open.org/cti/stix/v2.0/cs01/part2-stix-objects/stix-v2.0-cs01-part2-stix-objects.html#_Toc496714342



first_seen (optional) | timestamp | The beginning of the time window during which the SDO referenced by the sighting_of_ref property was sighted.
-- | -- | --
last_seen (optional) | timestamp | The end of the time window during which the SDO referenced by the sighting_of_ref property was sighted.

...

observed_data_refs(optional) | list of type identifier | A list of ID references to the Observed Data objects that contain the raw cyber data for this Sighting. For example, a Sighting of an Indicator with an IP address could include the Observed Data for the network connection that the Indicator was used to detect. This property MUST reference only Observed Data SDOs.
-- | -- | --

>This property MUST reference only Observed Data SDOs.


So we look at Observed data:

http://docs.oasis-open.org/cti/stix/v2.0/cs01/part2-stix-objects/stix-v2.0-cs01-part2-stix-objects.html#_Toc496714322

which has: 

first_observed (required) | timestamp | The beginning of the time window during which the data was observed.
-- | -- | --
last_observed (required) | timestamp | The end of the time window during which the data was observed.


So can a Observed Data first/last Observed time window be outside (entirely, or on either end) of the Sighting's time window as part of the Sighting's first_seen / last_seen properties?

**Comment by StephenOTT** [comment]
Notes from CTI TC mailing list:

From Allan Thomson:

>First of, the primary reason why Sighting has first_seen and last_seen is to support the ability to share Sightings without including any observed data object references.
>
>This is where a producer wishes to state that they saw an indicator and possibly how many times within the time window of the sighting but they do not wish or have the details of the observed data to share.
> 
>Therefore although this might seem duplicative for the time window properties initially,  it’s not.
>
>Secondly, the first_seen and last_seen of a sighting are optional. Therefore it is entirely compliant to have a sighting that connects an indicator (or any other sighting of pointer) and observed_data of that indicator where the time-window of the observed data is defined on the observed_data object itself but the sighting time window properties are not defined at all.
>
>Finally, is it highly likely that both sighting and observed_data time window properties should align for many cases -> Yes.
>
>Can you say that they definitely have to match in all circumstances -> No.

from Jason Keirstead

>Agree 100% with all Allen's comments.
>
>Another reason, is that you can sight any object in STIX, and the observed_data object is not always applicable. IE, I could be sighting an Identity object for a threat actor, and want to say I saw them active from Monday to Friday, and not have any observed_data attached to this.

**Comment by jordan2175** [comment]
What is the status of this @StephenOTT can this be closed?

**Comment by StephenOTT** [comment]
does a sighting time window have to encompass the observed data that the sighting refs?  Can the observed data be outside of the time window of the sighting? 

The above states that they don't have to be the same but does not clarify if the observed data has to be within the time window of a sighting when a sighting has dates applied ? 

I think it goes to what was the original intended usage of this object?

**Comment by rpiazza** [comment]
I think they are independent, although often related.  When you observe some fact, can be different then when you realize that it "means something".

I think this text from the spec makes this point:

>Sighting is distinct from Observed Data in that Sighting is an intelligence assertion ("I saw this threat actor") while Observed Data is simply information ("I saw this file"). When you combine them by including the linked Observed Data (observed_data_refs) from a Sighting, you can say "I saw this file, and that makes me think I saw this threat actor".

**Comment by jordan2175** [comment]
Based on this response from Rich P, I think we can close this question.  If you have further questions or concerns with this, please let us know.
