### ISSUE TITLE
Is the use of CPE in the SDOs inconsistent?

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#160]
There are two properties that suggest that a CPE be used to identify the software/os:

 - coa/os_execution_envs
 - malware/os_execution_envs

Others use an embedded relationship to a Software SCO (which has a CPE property) - for instance:

 - malware-analysis/operating_system

Should an embedded relationship to a Software SCO replace the CPE string for os_execution_envs to be consistent?

**Comment by jordan2175** [comment]
Similar to #220

**Comment by clenk** [comment]
Makes sense to me for these to be consistent and all use a relationship to `Software`.

**Comment by jordan2175** [comment]
Talked about this on the 2020-02-18 working call and the consensus was to make this change.

**Comment by jordan2175** [comment]
changes made
