### ISSUE TITLE
Discrepancy between ANTLR Grammar and Patterning text

### ISSUE THREAD

**Issue by ejratl** [oasis-tcs/cti-stix2#165]
In Section 9.5.1 Observation Expression Qualifiers, WITHIN has the following limitation "x MUST be a positive floating-point value." However, all of the examples show WITHIN as a positive integer and the ANTLR grammar explicitly allows for a positive integer in addition to a positive floating-point value. I recommend that the text be updated to explicitly allow a positive integer since this is the most common usage. "x MUST be a positive floating-point value." -> "x MUST be a positive floating-point or integer value."

**Comment by rpiazza** [comment]
Not to make a big deal about this, but now that I look at this - I would rather it says "x MUST be of type _float_ and have a positive value".  Our "type" float is expressed using a JSON Number, as is our "type" integer.  BTW, I always thought that "1" is a floating point number :-)

Once again, if any change for this would imply needing another WD - then unless we were going to do that anyway - I would leave it "as is".

**Comment by ejratl** [comment]
I agree that this is a not big deal. It can be addressed in a future revision if there are no other changes that will require another WD. I'd like to keep this issue as a reminder until it is addressed.

**Comment by jordan2175** [comment]
Changed the last sentence / clause to read:

> x MUST be a positive floating-point or integer value.
