### ISSUE TITLE
Should pattern_type be required?

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#167]
I'm starting to upgrade the elevator (and slider) for 2.1 WD05 - which means because the pattern_type property is now required, I need to add "pattern_type": "stix" to all of my tests.

I wonder if we should make pattern_type optional, with the default of "stix".

Everybody seems concerned about bytes on the wire...

**Comment by jordan2175** [comment]
I could go either way on this.  Do you want to bring it up on a working call?

**Comment by rpiazza** [comment]
Let's bring this up on the next call, and go with the consensus.

**Comment by jordan2175** [comment]
We talked about this on the 2019-11-12 working call and the consensus was to not make this change.
