### ISSUE TITLE
Can lists have duplicate items? Eg Labels

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#169]
Can lists have duplicate items? Consider labels, can labels property have multiple duplicate values ? `[1,1,2,3,4]`

**Comment by varnerac** [comment]
STIX lists may have duplicates. However, a particular STIX field of type list may put further restrictions on it. For example, the `network-traffic.protocols` field enforces a particular sort order. I think specifying that the list may not contain duplicates (i.e. a set) would be a valid restriction for some use cases. However, the general case of lists allows duplicates.

The `labels` property is little slippery, because the text mentions it as a "set of terms". I do not _think_ that "set" is normative here, but I am no expert on spec wording.

**Comment by jordan2175** [comment]
If we need to clarify any of this, please let us know.  But I think a list in general can have duplicate terms.  But I think, as Drew calls out, that some instances of the list may have stricter rules.  I think labels should probably be one of them. What do other people think?

**Comment by StephenOTT** [comment]
So I would propose that all list impl be "lightly" reviewed in the spec to confirm where text should be added to clarify if there are duplicates allowed in the specific impl of the property/list.

Further to @varnerac comment: @varnerac Are there properties that have lists with specific sort orders other than insert order? (FILO)

**Comment by varnerac** [comment]
`artifact.hashes` and `file.hashes`SHOULD have a sort order based on preferred hashes.

**Comment by StephenOTT** [comment]
@varnerac is that just how you interpret the list?  It's a normal Json list which maintains the order of insert.

**Comment by varnerac** [comment]
Yes.

**Comment by StephenOTT** [comment]
The email message SCO seems to have lots of lists that is a example of where better definition of duplicates support such as https://github.com/oasis-tcs/cti-stix2/issues/180

**Comment by jordan2175** [comment]
Really this is all called out in RFC 7493 and RFC 8259.  If JSON supports it, then we really support it. The general rule is, if we need or require more specific restrictions then we add them to the properties in question.  If we want to add additional restrictions to specific properties, please call out the properties and the proposed text for them.

**Comment by jordan2175** [comment]
We talked about this on 2019-11-12 and the consensus is to not do anything at this time and continue to allow duplicates.

**Comment by StephenOTT** [comment]
@jordan2175 what are the implications of this?  Does this mean that all Lists will support duplicates?  Are there specific properties that are type `List` that will not support duplicates?
