### ISSUE TITLE
Allow some data markings to reference externally defined policies

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-stix2#17]
We should allow some marking definitions to be referenced in an external document like TOU and other Statement documents.  To do this, we will also need to add a hash to make sure that nothing gets changed out from underneath the consumers.

**Comment by johnwunder** [comment]
IMO this isn't a priority for 2.1

**Comment by johnwunder** [comment]
F2F: We discussed this, Bret is willing to close this.
