### ISSUE TITLE
[2.1] why is a bundle not considered a Stix Object?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#170]
A bundle has a type and Id property. 
The definition of the bundle explains that it is a wrapper and does not have meaning other than as a wrapper for the transient content. 

In 1.8 it defines that the term Stix Content was chosen as the term for the super grouping of the bundle as Stix Objects. 

My question is: why go to the effort to separate the bundle?  Why not consider the bundle a Stix Object?

**Comment by jordan2175** [comment]
Because if you treat it as a STIX Object, then people would expect they could ask for a given Bundle from a TAXII server later on.  A Bundle is simply just a JSON structure to transmit JSON STIX Objects.  As you know, you need an "outside" container for JSON.  This is what Bundle is. So a system will read the contents from the bundle and then throw the bundle wrapper away.

**Comment by StephenOTT** [comment]
Okay so to clarify: the structure is because taxii is setup to "deliver Stix Objects" ? 

When you say throw away the container, are you saying the id of the container is throw away ? Or you do include the Id of the bundle as part of the bundle's "contents"?

Thanks

**Comment by jordan2175** [comment]
The Bundle ID is thrown away.  TAXII does not use the Bundle BTW, it has its own object, the TAXII Envelope.

**Comment by StephenOTT** [comment]
Okay.  So given this. I think it would be important for implementers to understand this and the underlying logic and usage.  @jordan2175  you clearly have lots of internal knowledge about the purpose and usage.  But the docs do not explain this and the expected / planned / originally intended usage.

I would propose we retitle this issue and adjust it to account for providing some explanation to how the bundle was expected to be used and its parallels with the taxii spec. (many / most? that implement STIX will expect it to be used by TAXII.  So if there are expectations thats taxii spec is downloading to STIX, then lets document this and provide the mental model for people to understand).

**Comment by jordan2175** [comment]
Is this not clear in the TAXII spec?  https://docs.google.com/document/d/1EsiWY7TGqt9yH6QUXv4c-opXSr3wR0TDMt8Q0yJjpoo/edit#heading=h.2njtsnfo6dhz

If there are specific suggestions that can make things easier to understand, please propose exact changes.

**Comment by StephenOTT** [comment]
More the issue that I have to now read the taxii spec to make sense of the stix spec.  I should not have to understand taxii in order to understand stix.

**Comment by jordan2175** [comment]
No, STIX is about STIX and TAXII is about TAXII.
