### ISSUE TITLE
[2.1] course of action: action_reference: Confusing terms?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#171]
Section 4.3 outlines course of action with a action reference(AR). The AR says that AR cannot be used if the action_bin is used. 

A "reference" seems to suggest that it is a "external reference" to provide additional context.  Such as the AR providing context to where the action_bin commands came from.  If you have a action_bin, where can you store the source of those commands ? (Because there would likely be a source page that explains the sudo commands needed, and the bin is the actual prepared "commands".  )

**Comment by jordan2175** [comment]
You either add the command directly to the object and store that in the action_bin property or your link to it via the action_reference property.
