### ISSUE TITLE
[2.1] use of the precision property in Location vs count of decimal places in lat and long?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#174]
What is the design decision / background around using the "precision" property for Location SDO?  

A similar requirement was originally seen with the timestamp, but precision was calculated with count decimal places.

Why is lat and long's precision not calculated based on the number of decimal places provided?

**Comment by varnerac** [comment]
The JSON parser won’t capture the number of digits after the decimal. That’s not how floating point numbers work. We can get away with it on the timestamps because they are strings.

**Comment by StephenOTT** [comment]
Which Json parser ? Is that not a impl concern on how their parser treats that float value? A geojson will put their point values in a array of [lat, long] and it has whichever precision you want.

**Comment by varnerac** [comment]
All JSON parsers. E.g. Python (https://repl.it/repls/SpatialVividCheckpoint):

```
import json
print(json.loads('{"foo": 1.0}'))
print(json.loads('{"foo": 1.0000000}'))
# {'foo': 1.0}
# {'foo': 1.0}
```

1.0000000 is the representation of a floating point number. But, floating point numbers are not fixed point numbers.  We can't "see" the actual precision of a floating point number in JSON.

There are other good reasons in the specific case of lat/lon. Precision is in terms of meters. The length of a decimal degree varies dramatically between the North Pole and the equator. It'd be cruel to make users deal with that.

**Comment by StephenOTT** [comment]
Great. Thanks 👍🏻
