### ISSUE TITLE
[2.1] Background for why SCOs were made to be bundleable (support relationships with other StixObjects), but versioning properties were not explicitly added

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#176]
in section 3.6 for Versioning is reads:

>In STIX 2.1, SCOs do not explicitly have those three versioning properties. Therefore, a SCO cannot be versioned unless custom properties (discussed in section ​11.1​)​ are used. Producers who do this SHOULD​ use the property names ​created_by_ref​, ​revoked​, ​created​, and ​modified​.

What is the background on this?  Why was SCOs made to support relationships with other objects ("outside of the cyber observable container"), but the rest of the typical common properties were not added?

Given this is shown as an option for producers (as per 3.6), what were the original reasons for the lack of adding those common props, and what are the implications?

**Comment by StephenOTT** [comment]
Building on this:

In 3.2 for the spec_version prop it states:

>If objects are found where this property is not present, the implicit value for all STIX Objects other than SCOs is ​2.0​. Since SCOs are now top-level objects in STIX 2.1, the default value for SCOs is 2.1​.

These details that have been injected into the spec are exponentially increasing the complexity / exception handling and contextual knowledge required to interpret objects...

**Comment by varnerac** [comment]
I'm not a STIX expert, but I'll take a shot at this based on what I remember from calls.

> Given this is shown as an option for producers (as per 3.6), what were the original reasons for the lack of adding those common props, and what are the implications?

The idea is that observables represent an object "fact" at a point in time, and really cannot be revised. For example, a file "resume.pdf" had an MD5 hash of `"dd07..."` with particular characteristics at a particular time. How would we revise it? I think of them as immutable factoids, though others may disagree.

> can i now have a SCO that is 2.0 in the top level? or must it be in a container?

You cannot have a 2.0 top-level SCO, because cyber observables outside of Observed Data objects didn't exist until 2.1. Do you have proposed text to make this idea clearer?

**Comment by rpiazza** [comment]
@StephenOTT,

Continuing with what @varnerac said above.

On the calls there was much controversy about whether an SCO should be mutable (i.e., versionable).  The argument in favor is that you might find out something new about an SCO, and you want to add it.  For instance, you might have an existing File SCO, and then you find out its size.  To support this, a compromise was arrived at - summarized by the text you referred to.
You can version an SCO with custom properties, but using the same names of the versioning properties that already exist.

**Comment by StephenOTT** [comment]
@rpiazza @varnerac Thanks for the details:
So the way I am reading the docs while going through a impl seems to raise questions to if the text is clear on what you wrote:

1. @rpiazza based on what you wrote, "custom properties" means `x_` properties?  "x_spec_version" ?  "Custom properties" in the stix spec has specific definition so want to be clear.  The SCOs definitions such as 6.1 show the properties "spec_version​, ​object_marking_refs​, g​ ranular_markings​, ​defanged​, ​extensions" as `Optional Properties`, which just means they are not required.

1. @varnerac from what I can find in the spec, there does not appear to be text to defines that 2.0 objects cannot be used outside of the container. 

1. For spec_version: `The version of the STIX specification used to represent this object.
The value of this property ​MUST​ be ​2.1​ for STIX Objects defined according to this specification.
If objects are found where this property is not present, the implicit value for all STIX Objects other than SCOs is ​2.0​. Since SCOs are now top-level objects in STIX 2.1, the default value for SCOs is 2.1​`, why is this implemented to create two different defaults?  If SDOs require a spec_version with 2.1, why not have SCOs have the same requirement?  Why create what seems to be a artificial requirement of having a default value on the SCOs' spec_version?

**Comment by varnerac** [comment]
>  there does not appear to be text to defines that 2.0 objects cannot be used outside of the container

So, I think the 2.0 spec defines this in the affirmative. In STIX 2.0 Part 1:

> The full set of STIX Domain Objects and STIX Relationship Objects are known as STIX Objects.

And 2.0 Part 2's glossary:

> STIX Object - A STIX Domain Object (SDO) or STIX Relationship Object (SRO)

**Comment by StephenOTT** [comment]
Sorry i was speaking about the 2.1 spec: Does the 2.1 spec say that 2.0 SCOs cannot be used outside of the deprecated container?

Additional angle: Does a 2.1 Bundle support support objects of various spec_versions? (2.0 and 2.1).  If not, where does it say this? as does not appear in the Bundle description of section 8.  But if it does support it, then it would be very easy for a impl to start allowing 2.0 SCOs directly in the bundle.  The point being the level of complexity that starts to be introduced for impl and conformance to the spec: A bundle now needs to read all SCOs in a bundle and validate their spec version to ensure that a 2.0 SCO is not there.

**Comment by varnerac** [comment]
> Does a 2.1 Bundle support support objects of various spec_versions? (2.0 and 2.1). If not, where does it say this? 

It does. The Bundle object dropped `spec_version` in 2.1. We shifted it to the child Objects to allow multiple STIX versions in a single Bundle.

> But if it does support it, then it would be very easy for a impl to start allowing 2.0 SCOs directly in the bundle.

Your Bundle validation code should identify this. I get what you are saying that this could be a "gotcha."

> there is then a implicit rule of "2.1 Bundles must validate that 2.0 SCOs are not present"

While this is true, I think this is the wrong way to approach it. You could also say "2.1 Bundles must validate that Marking Definitions are not present at the top level". It needs to be evaluated in the affirmative:

> A Bundle is a collection of arbitrary STIX Objects grouped together in a single container.

A STIX 2.0 Cyber Observable is not a STIX Object.

**Comment by StephenOTT** [comment]
@varnerac what i am seeing at a impl level is that users end up having to create duplication or feature flags (look for what spec version it is) at the bundle level because typical impl OOP inheritance looks to be a "no-go".  Yes we can use a affirmative rule as you stated in the spec; but the impl is a different animal.

Can you give a simple code sample of how you would see this impl without having to now duplicate all of the objects or without having to check for the feature flag?

---

Do you have any insights into my number 3 above:

>For spec_version: The version of the STIX specification used to represent this object. The value of this property ​MUST​ be ​2.1​ for STIX Objects defined according to this specification. If objects are found where this property is not present, the implicit value for all STIX Objects other than SCOs is ​2.0​. Since SCOs are now top-level objects in STIX 2.1, the default value for SCOs is 2.1​, why is this implemented to create two different defaults? If SDOs require a spec_version with 2.1, why not have SCOs have the same requirement? Why create what seems to be a artificial requirement of having a default value on the SCOs' spec_version? When Stix "2.2" arrives, are you not now going to add spec_version as a required field on SCOs? (just like what was done for SDOs), why create that baggage?

**Comment by varnerac** [comment]
Yes, the `2.1` default for SCOs is problematic. If I have a custom object, I don't know how to tell if it is an SCO or SDO. Therefore, I cannot accurately predict if the implicit `spec_version` should be `2.0` or `2.1`. Does anyone know a way to determine if an arbitrary custom object is an SDO or SCO?

**Comment by StephenOTT** [comment]
The Network Traffic SCO seems to be a example where a update would occur?

The `end` property is a Timestamp: `If the ​is_active​ property is true, then the ​end​ property
MUST​ ​NOT​ be included.`  Therefore a network traffic item could be reported and then subsequently updated rather than replaced with a new object ?

**Comment by jordan2175** [comment]
Yes there are some known and yet unknown issues with these compromises.  This was discussed at during no fewer than 2 face to face meeting and many working calls.  In the end, compromise led us to where we are at.  So yes, you can update a SCO if you really want to, but that means you would just add the common properties to the object.  I personally believe most will just release a new object since the deterministic IDs will change.  So the trade off is between deterministic IDs and versioning.
