### ISSUE TITLE
[2.1] Encryption Algro Enum? should be a open-vocab?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#177]
There may be proprietary algros or non-public algros used: why is not a open-vocab?

Partial duplicate of https://github.com/oasis-tcs/cti-stix2/issues/30 (but issue 30 is about expanding the enum vs this issue is questioning why its a enum to begin with)

**Comment by jordan2175** [comment]
The TC decision at the time was this should be locked down.  Please feel free to bring this up as an email discussion.  I am not sure the TC will want to do this for 2.1, but maybe for 2.2.  But I could be wrong.
