### ISSUE TITLE
[2.1] 6.6 can body_multipart support duplicate instances of mime-part-type ?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#180]
In section 6.6 can body_multipart support duplicate instances of mime-part-type ?

**Comment by jordan2175** [comment]
No, that would be a violation of I-JSON RFC 7493 as called out in Section 1.6.12

**Comment by jordan2175** [comment]
I was wrong, JSON does allow this and this should be allowed. We talked about this on 2019-11-12.
