### ISSUE TITLE
[2.1] Inconsistent title vs type name: 6.6.2

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#181]
Section 6.6.2 the header reads "Email MIME Component Type" but the type name says "mime-part-type".  Should the header be renamed to "Email MIME Part Type" ?

**Comment by rpiazza** [comment]
Network Socket Extension is named socket-ext.  If we think its worth changing mime-part-type, we should change this one too.  I'm fine either way.

**Comment by jordan2175** [comment]
suggestion made in WD06
