### ISSUE TITLE
[2.1] 6.7.6 windows pe binary file extension: time_date_stamp "must be precise to the second" ?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#183]
The time_date_stamp has a requirement for the time stamp to be precise to the second.  What is the background on this?  I ask because it seems like a unique requirement outside of the usage of a Stix timestamp in the other sections of the spec.

**Comment by jordan2175** [comment]
I believe the rational is that some tools in the malware analysis trade craft can only produce second level precision.

**Comment by StephenOTT** [comment]
@jordan2175  why does a production limitation require a validation constraint of the object?  Did you mean that the consumers of the STIX object can only consume timestamps with second precision?

**Comment by StephenOTT** [comment]
@ikiril01 can you provide some context on this?  It seems that this constraint is based on a producer's capability to generate a specific precision?  Is this correct?

**Comment by ikiril01** [comment]
@StephenOTT yes, this is correct - producers (tools, etc.) should not be able to generate other precisions since PE timestamps are precise to the second but do not support further precision. See https://docs.microsoft.com/en-us/dotnet/api/system.reflection.portableexecutable.coffheader.timedatestamp?view=netcore-3.0

**Comment by StephenOTT** [comment]
I would suggest we add this context + the link to the description of the field.  Similar description was provided for other context specific fields in the spec.

@ikiril01 @jordan2175
