### ISSUE TITLE
[2.1] 6.12.2 HTTP Request Extension: request_header dictionary: unknown headers vs no header definition?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-stix2#184]
In the HTTP request extension, the `request_header` property is a optional dictionary.  How do you represent "did not capture / unknown headers / not sharing headers in the CTI" (usually with not providing that property  vs "no headers were provided"

Can you have an empty dictionary?

seems to be a carry over from work done in: https://github.com/oasis-tcs/cti-stix2/issues/137

**Comment by StephenOTT** [comment]
@jordan2175 are you saying that a Dictionary type can be an empty dictionary?  `{}`

**Comment by rpiazza** [comment]
This text comes from section 2.12 List:

Empty lists are prohibited in STIX and MUST NOT be used as a substitute for omitting the property if it is optional. If the property is required, the list MUST be present and MUST have at least one value.

Perhaps we should include similar text in section 2.3 Dictionary?

**Comment by jordan2175** [comment]
We talked about it on 2019-11-12, the editors will take a look to verify who vast this change would be, and then if it is simple, we will do it, if not, we will come back to the working group with a proposal.

**Comment by jordan2175** [comment]
After some analysis that all dictionaries are currently optional, we added the following text to section 2.3. 

> Empty dictionaries are prohibited in STIX and MUST NOT be used as a substitute for omitting the property if it is optional. If the property is required, the dictionary MUST be present and MUST have at least one key value pair.
