### ISSUE TITLE
Text in Network Traffic incorrectly describes src_ref and dst_ref

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#19]
The src_ref and dst_ref properties in Network Traffic have descriptions that refer to a list, but the property itself is a single value. The description should be corrected.

**Comment by ikiril01** [comment]
The corrected descriptions should be the following:

**src_ref**
Specifies the source of the network traffic, as a reference to an Observable Object.

The object referenced MUST be of type ipv4-addr or ipv6-addr or mac-addr or domain-name (for cases where the IP address for a domain name is unknown).

**dst_ref**
Specifies the destination of the network traffic, as a reference to an Observable Object.

The object referenced MUST be of type ipv4-addr or ipv6-addr or mac-addr or domain-name (for cases where the IP address for a domain name is unknown).

**Comment by ikiril01** [comment]
These changes have been made to the draft STIX 2.1 specification.

**Comment by jordan2175** [comment]
Ivan has made these changes in the official 2.1 documents
