### ISSUE TITLE
Process Object missing property "name"

### ISSUE THREAD

**Issue by emmekappa86** [oasis-tcs/cti-stix2#190]
Checking the table of Process Object (6.13.1), it seems property "name" may be missing. This consideration comes from the example that follows ("Basic Process") immediately showing the aforementioned property ("name": "gedit-bin").

**Comment by jordan2175** [comment]
We talked about this on 2019-11-12 and this is not needed/valid.

**Comment by jordan2175** [comment]
This seems to be dropped from 2.0, need to verify that it was not dropped on purpose.

**Comment by jordan2175** [comment]
This was removed due to github issue 47

**Comment by jordan2175** [comment]
So no action will be taken.

**Comment by StephenOTT** [comment]
thanks for ref to issue #47.  Helps to clarify 👍
