### ISSUE TITLE
'hashes' MUST come from an open vocabulary

### ISSUE THREAD

**Issue by clenk** [oasis-tcs/cti-stix2#192]
All `hashes` type properties say the values MUST come from the `hash-algorithm-ov`, but saying something MUST come from an open vocabulary makes it a de facto SHOULD because it can contain any value. There was a call on 2019-08-06 to discuss this with the following outcome (from @ejratl's great meeting notes):

> Possible solutions discussed included:
> 1) Do nothing
> 2) Add some clarifying text 
> 3) Create a mini-hashes vocab
> 4) Instead of saying that a property uses the hashes vocab, call out the hashes that are valid for that property....
>
> During the meeting there was a straw poll taken, which resulted in a 9-2 consensus to do nothing for 2.1 and re-address the issue in a future revision. The problem was acknowledged, but the majority felt that implementers would interpret it the same way as the spec intended.

I'm just creating an issue here so it doesn't get forgotten for the next version of the spec.

**Comment by StephenOTT** [comment]
Why does it make it a should?  If the open vocab is a managed list then that managed list must contain the value.  The fact the list is "open" / open to change beyond what is defined in the spec is a factor of the vocab not a factor of the object using the hashes prop.

**Comment by clenk** [comment]
My thinking was that if a value MUST come from an open vocabulary, it's the same as saying it MUST be any string, since open vocabs are just suggested values. Section 2.14 Open Vocabulary contains no MUST requirements, only SHOULDs and MAYs.

> The value of the property SHOULD be chosen from the suggested vocabulary, but MAY be any other string value.

The requirement on `hashes` properties could be interpreted to mean one of several different things: 
* there's really no restriction on `hashes` values
* the MUST on the `hashes` property replaces the SHOULD in the Open Vocab type description, effectively treating `hash-algorithm-ov` as if it were an enum
* the values SHOULD be from the suggested values in the open vocabulary

I think the third interpretation might be closest to the intent of the spec because it's kind of a middle ground between the other two, but as written I find it ambiguous.

**Comment by jordan2175** [comment]
The problem we were trying to fix was undoing the mistake we made with reusing the hashes types for external references.  A lot of these issues would just go away if we could change that to use say a string that is a SHA256 hash or something.  This first came up shortly after STIX 2.0 was released and people started writing code for it.

**Comment by allant0** [comment]
the amount of time spent debating already exceeds the time necessary to change this to SHOULD and be done with it. I suggest we *should* change it to just *should* and move on.

**Comment by jordan2175** [comment]
After looking back at this issue I think the problem is with the text on External References.  We say in the document that property tables can be more strict than the general definitions.  Right now the text for hashes on the External References says the following:

> Dictionary keys MUST come from the hash-algorithm-ov open vocabulary.
>
> As stated in Section 2.7, to ensure interoperability, a SHA-256 hash SHOULD be included whenever possible.

What I believe we need to say here to address @clenk 's concern is:

> Dictionary keys MUST come from the **`entries currently defined in the`** hash-algorithm-ov open vocabulary.
> 
> As stated in Section 2.7, to ensure interoperability, a SHA-256 hash SHOULD be included whenever possible.

**Comment by jordan2175** [comment]
We talked about this on 2020-02-11.  We should say "entries defined in the".  Consensus on the call was to make this change.

**Comment by jmgnc** [comment]
Thinking a bit more on this, maybe, say, `entries listed in the open vocab table`? and just be explicit about it?

**Comment by jordan2175** [comment]
This has been changed.  The text now reads:

> Dictionary keys MUST come from one of the entries listed in the hash-algorithm-ov open vocabulary.

**Comment by clenk** [comment]
I noticed this change was made for `external-reference`. For consistency, does the change also need to be made to `artifact.hashes`, `file.hashes`, `ntfs-ext.hashes`, `windows-pebinary-ext.file_header_hashes`, `windows-pe-optional-header-type.hashes`, `windows-pe-section-type.hashes`, and `x509-certificate.hashes`? (basically everywhere the `hash-algorithm-ov` is used)

**Comment by jordan2175** [comment]
Rich P looked at those and they are different uses.  Those are using hashes to describe what is be seen in the wild.  External References is the only place we could find where the producer is using hashes to do something.
