### ISSUE TITLE
Deterministic IDs with no contributing properties

### ISSUE THREAD

**Issue by clenk** [oasis-tcs/cti-stix2#193]
In the case where an SCO's ID-contributing properties are all optional and none of them are provided, falling back to UUIDv4 seems to be the understood solution, but this isn't stated in the spec.

@rpiazza suggested adding the following to section 2.9 as the fourth bullet point of the paragraph which begins “STIX Cyber-observable Objects SHOULD use UUIDv5…”
> * If the contributing properties are all optional, and none are present on the SCO, then a UUIDv4 SHOULD be used.

This was discussed on the 2019-09-03 working call. @ejratl’s meeting notes mention these outcomes:

> Fix the examples in the spec. Flag this issue – we won’t make the changes if this is the only normative change, but if we have to rev the spec, then we will fix this at that time.

I believe the examples were fixed; I'm just creating an issue here so it isn't forgotten when the next version comes around.

**Comment by rpiazza** [comment]
@jordan2175 - now that we are making a new WD - maybe we could add this...?

**Comment by jordan2175** [comment]
In the spirit of where we left this on the working call, I think now would be the time to do it.

**Comment by jordan2175** [comment]
In Section 2.9 we added the first bullet here and modified the second to be:

> * If the contributing properties are all optional, and none are present on the SCO, then a UUIDv4 MUST be used. 
> * Producers not following these rules MUST NOT use a namespace of 00abedb4-aa42-466c-9c01-fed23315a9b7 and SHOULD use UUIDv4 in cases where the id would not be unique.
