### ISSUE TITLE
[2.1] Network Socket options property description implies all options begin with SO

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#194]
This text is in the description of the options property of network-socket-ext:

``Specifies any options (SO_*) that may be used by the socket, as a dictionary. ``

This could imply that only keys that begin with SO are allowed as keys.  But there are other options, that don't begin with SO - e.g., IP_MULTICAST_LOOP

Also see: http://man7.org/linux/man-pages/man7/ip.7.html

Additionally, STIX 1.1.1 (CybOX) includes other options:

http://cybox.mitre.org/language/version2.1/xsddocs/objects/Network_Socket_Object.html

Suggest we tweak the text as follows:

``Specifies any options (e.g., SO_*) that may be used by the socket, as a dictionary. ``

**Comment by jordan2175** [comment]
This change was made in 6.12.4.1
