### ISSUE TITLE
Small mistake within "Sighting Embedded Relationships" table 

### ISSUE THREAD

**Issue by emmekappa86** [oasis-tcs/cti-stix2#195]
Within the "Embedded Relationships" table of section 5.2.2 (page 131), "observed_data_refs" should be described as "list of type identifier (of type **observed-data**)" instead of "list of type identifier (of type SCO)".

**Comment by jordan2175** [comment]
Rich and I discussed this and agree that this is probably what it was meant to be and probably got changes to SCO en mass when we were fixing the top-level SCO references.  However, we will clarify this with the TC.  We will mark this is done for now, but may need to reopen at a later time.
