### ISSUE TITLE
Small mistake within "Infrastructure" example in 4.7.2

### ISSUE THREAD

**Issue by emmekappa86** [oasis-tcs/cti-stix2#197]
Within the example of a bundle containing an "Infrastructure" Object in paragraph 4.7.2 (pages 77-78), two Relationship objects have the same "id" ("relationship--7aebe2f0-28d6-48a2-9c3e-b0aaa60266ef").

**Comment by rpiazza** [comment]
@emmekappa86 - once again, good catch!

@ejratl - could you check the rest of the infrastructure examples in the Appendix to see if there are any other duplicate ids?  Thanks!

**Comment by emmekappa86** [comment]
@rpiazza @ejratl - I was doing some tests with the examples in Appendix C and I created a related issue (#198 )

**Comment by jordan2175** [comment]
Changes made
