### ISSUE TITLE
Issues in "Appendix C"

### ISSUE THREAD

**Issue by emmekappa86** [oasis-tcs/cti-stix2#198]
While reviewing the examples of "Appendix C", I noticed the following things:

- Both "relationship--2f340a76-edef-443d-a203-bede067c0bb0" and "relationship--8386f241-b583-4c59-9056-a3b0db596d93" have been used twice (each) for Relationship objects that are not the same
- Id "infrastructure--d09c50cf-5bab-465e-9e2d-543912148b73" has been also used twice but, in this case, I do not see any problem as the two objects are exactly the same
- Images in C.1.1 and C.1.2 have relationships labeled as "used-by", but I would have expected to see labels "uses" instead (and the direction of the arrows reversed). Now, I am actually not sure if this kind of "reversing" is acceptable for all STIX Relationships. Is it specified anywhere in the standard?
- One relationship of the image in C.1.4 has the wrong label. The relationship linking the infrastructure object to the domain-name one should be "communicates-with"
- At page 293, id's value "domain-name--224dd5a2-d2db-5b8d-91f9-124a0c0c8546" is missing the closing quotation mark

**Comment by rpiazza** [comment]
@emmekappa86 

Thanks for looking so closely at the examples!  We will be making needed changes this week.

**Comment by jordan2175** [comment]
We have fixed bullets 1, 2, and 5.  The third and forth bullets about the pictures is correct and we need to get them replaced.  We will ask @ejratl to do that.

**Comment by jordan2175** [comment]
Bullet point 3 is done. Just bullet point 4 is left to fix.

**Comment by ejratl** [comment]
Bullet point 4 was fixed by changing both the json and the graphic to use the relationship consists-of.

**Comment by jordan2175** [comment]
Changes have been accepted, closing
