### ISSUE TITLE
Add valid_from and valid_to to relationship

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#20]
Many relationships are only valid for some time period...for example, malware may only be used by a threat actor for some period of time. Optional valid_from and valid_to properties would let you capture that, when relevant.

**Comment by gtback** [comment]
We should be careful of how this interacts semantically with (for instance) the `valid_from` field on Indicators.

**Comment by JasonKeirstead** [comment]
I think that first_seen and last_seen makes more sense given the information being captured here.

**Comment by lpingree** [comment]
Agreed

**Comment by lpingree** [comment]
I think it would be nice to also have a "times seen" but the concurrency and state may be problematic.

**Comment by skelley1** [comment]
This issue was superseded by our solution to Issue #11.
