### ISSUE TITLE
resolves_to_refs need to be un-deprecated unless improvements are made to patterning

### ISSUE THREAD

**Issue by JasonKeirstead** [oasis-tcs/cti-stix2#202]
On some SCO objects relationships such as resolves_to_refs have been deprecated in favour of the new SCO relationship mechanism. However, we have not yet codified how one is to traverse these relationships inside a STIX pattern.

As a result - there is now no way to match in a pattern against an SCO object that is tying an IP address and a domain name or an IP and an ASN.

We have this use case actually in use today in the wild - as do many others - and are unsure how to bring this forward to 2.1 without referencing deprecated properties.

I think that either guidelines need to be added as to how to handle this use case that exists in 2.1 (stating that the deprecated properties are not actually depcreated...) or, more simply, resolves_to_refs and belongs_to_refs should not be marked as deprecated in the various SCO objects until this is handled properly.

**Comment by allant0** [comment]
Simplest approach is just remove deprecated marking. Given that people can define their own relationships anyway this is the easiest common sense way to solve the problem for now.

**Comment by JasonKeirstead** [comment]
@allant0 I agree with that approach.

**Comment by rpiazza** [comment]
+1 - easy to do in the spec, and shouldn't have any real effect on any current implementations.

**Comment by jordan2175** [comment]
We talked about this on the full TC call for January 2020, and the consensus was to make this change.

**Comment by jordan2175** [comment]
Changes were made to 1x6.4.1, 2x6.8.1, and 2x6.9.1 for a total of 5 changes.

**Comment by ejratl** [comment]
In Section 9.8 in the Patterning document, the reference to resolves_to_refs still says that it is deprecated.  "Matching on a Domain Name with IPv4 Resolution - Deprecated in 2.1, uses resolves_to_refs Relationships" should revert back to "Matching on a Domain Name with IPv4 Resolution".

**Comment by jordan2175** [comment]
This has been fixed.
