### ISSUE TITLE
Small mistake within "Domain Name" Example in 6.4.2

### ISSUE THREAD

**Issue by emmekappa86** [oasis-tcs/cti-stix2#203]
Within the example of a "Domain Name" Object in paragraph 6.4.2 (pages 142/143), there is an extra "comma" after the last property ("value": "example.com"). Furthermore, a closing quotation mark is missing for value "domain-name--3c10e93f-798e-5a26-a0c1-08156efab7f5" in the relationship object.

**Comment by rpiazza** [comment]
Good catch @emmekappa86!

We will fix it

**Comment by jordan2175** [comment]
This got fixed when we took care of issue 202.
