### ISSUE TITLE
Minor property naming issues

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#204]
The spec doesn't really doesn't restrict the name of a property very much.  For instance, by omission we allow non-alpha-numeric characters.  Additionally, a property name or type can start with a digit (remember, custom properties only SHOULD start with "x").

I also noticed that all property names for properties with lists as values are plural words - except body_multipart.  Should the spec say something about this?  Should we change the name of body_multipart?

**Comment by allant0** [comment]
the rules for naming are ultimately dictated by JSON rules themselves as orgs can add properties that are not bound by STIX rules but bound by JSON rules themselves. STIX naming should be consistent but we need to make sure people know that they have to handle objects and properties that are not part of STIX within the STIX content as most vendors are likely having to extend STIX to add their own objects and/or properties.

**Comment by rpiazza** [comment]
@allant0 - actually, the way the spec is written, it just says JSON is a mandatory serialization, but others are possible - see section 1.6.12.  Other serializations (e.g. XML) have rules about tag names.  Obviously, we can't write the specification for every possible serialization language - but restricting property and type names to the commonly assumed "identifier" rules, would be an improvement.

**Comment by jordan2175** [comment]
Talked about it on the working call on 2020-01-28.  John-Mark strongly supports adding the clarifying text.  Maybe not fix body_multipart though.  Consensus on the call is to make this change.

**Comment by jordan2175** [comment]
We added the following text to section 3.1 first paragraph to address this issue. The text added is:

> Type names and property names MUST begin with a letter character (for example - in ASCII that would be a through z).
