### ISSUE TITLE
Small mistake within "Network Traffic" Example in 6.12.1

### ISSUE THREAD

**Issue by emmekappa86** [oasis-tcs/cti-stix2#205]
Within the example of a "Network Traffic" Object in paragraph 6.12.1 (pages 176/177), there is an invalid UUID ("ipv4-addr--4d22aae0-2bf9-5427-8819-e4f6abf20a5300" in the first "ipv4-addr" object has two extra "zeroes").

**Comment by jordan2175** [comment]
That has been fixed.
