### ISSUE TITLE
Remove the size limit on artifact objects

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#21]
In STIX 2.0, artifact objects are limited to 10MB. This was done to prevent parsers, which sometimes can't handle bigger files, from choking on the JSON. Discussion on Slack and the mailing list suggests that it might be fine to just remove the limit, because many parsers are able to deal with larger files. Removing the limit would then allow for the submission of larger files directly in STIX (vs. via URL).

If we don't remove the limit we should at least properly define it as either 1024 x 1024 (MiB) or the "correct" 1000 x 1000.

**Comment by adulau** [comment]
IMHO, removing the limit is the only option ;-)

**Comment by ikiril01** [comment]
I'm fine with removing the limit.

**Comment by cheolholee75** [comment]
I also agree with removing the size limit

**Comment by jordan2175** [comment]
This was done back in working draft 01 just never closed.
