### ISSUE TITLE
Should text about the names of custom object properties be added to custom object extensions

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#212]
Should we add this text to section 11.3.1?  It is in 11.2.1...

The name of a property of a Custom Object ***Extension*** MUST be in ASCII and MUST only contain the characters a–z (lowercase ASCII), 0–9, and underscore (_). The "x_" prefix as described in section 11.1.1 MAY be used.

**Comment by jordan2175** [comment]
This was an oversight and the following text was added as the last bullet point in 11.3.1

> The name of a property of a Custom Object Extension MUST be in ASCII and MUST only contain the characters a–z (lowercase ASCII), 0–9, and underscore (_). The "x_" prefix as described in section 11.1.1 MAY be used.
