### ISSUE TITLE
Patterns: Parentheses with multiple Qualifiers

### ISSUE THREAD

**Issue by clenk** [oasis-tcs/cti-stix2#214]
It is not clear to me how parentheses interact with the requirement from #70 that an Observation Expression MUST NOT have more than one Qualifier of a particular type.

Is the following pattern valid?
```
(<expr1> AND <expr2> REPEATS 2 TIMES) REPEATS 3 TIMES
```
If the requirement does not apply to parenthesized observation expressions (i.e. a parenthesized group doesn't count as an Observation Expression), then you could just use parentheses to get around this requirement. For example the following would be valid:
```
(<expr1> WITHIN 1 SECONDS) WITHIN 5 SECONDS
```
If the requirement does also apply to parenthesized observation expressions, then the following pattern would be invalid - how would you write it so it's valid?
```
(<exprA> FOLLOWEDBY <exprB> REPEATS 2 TIMES) REPEATS 3 TIMES
```
I guess you could expand it out by replacing REPEATS with ANDs and copying the expression being repeated, but I don't know that similar expansion is possible for other qualifiers like WITHIN or START/STOP. Is it okay if that pattern is invalid?

I see downsides to having the restriction on duplicate qualifiers apply to parentheses and to it not applying to parentheses but don't see in the spec which one I should implement.

**Comment by jordan2175** [comment]
Talked about this on the 2020-02-18 working call and the consensus was to push this off to a future release when we look at more patterning issues.

**Comment by JasonKeirstead** [comment]
Parens do not make new observation expressions, so to me this is very clear.

"(i.e. a parenthesized group doesn't count as an Observation Expression), then you could just use parentheses to get around this requirement."

No you can't, because Parens do not start a new Observation Expression in the first place.

**Comment by clenk** [comment]
I was interpreting a parenthesized group as something other than an observation expression. Otherwise I think none of the above patterns would be valid.

----

What if we added text something like the following to Section 9.5, just before 9.5.1:

> When used, parentheses MUST surround at least two Observation Expressions.

And also changed this sentence in 9.5 (2nd paragraph)

> One or more Observation Expression Qualifiers MAY be provided after the closing square bracket or closing parenthesis of an Observation Expression.

to

> One or more Observation Expression Qualifiers MAY be provided after the closing square bracket of an Observation Expression or closing parenthesis around a group of Observation Expressions.

**Comment by srrelitz2** [comment]
Merged already - close item
