### ISSUE TITLE
Are custom properties allowed at any "level" or should they only be allowed in TLOs

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#215]
For instance, can I add a custom property to `external_references`, or `email_mime-part`?  Can I added them to extensions - e.g., `socket-ext`?

Here is an example:
```
{
    "extensions": {
        "socket-ext": {
            "address_family": "AF_INET",
            "is_listening": true,
            "options": {
                "IP_MULTICAST_LOOP": true
            },
            "x_elevator_local_address": "198.51.100.2"
        }
    },
    "id": "network-traffic--fb055025-dd4f-5fd0-bf8a-c81de67d1eb9",
    "protocols": [
        "tcp"
    ],
    "type": "network-traffic"
}
```
This example was produced by the elevator, with the *use-custom-properties* option enabled.  STIX 1.x had a `local_address` property on the CybOX socket object.  The `local_address` is related specifically to the socket.  It's a stretch to say it is part of the network traffic object.

There is no downside to allowing custom properties at all levels, although there might need to be some text tweaking in the spec to avoid ambiguity.  This statement from section 11.1 could be construed to mean that custom properties can only exist at the top level.

**There will be cases where certain information exchanges can be improved by adding properties to ***STIX Objects*** that are neither specified nor reserved in this specification; these properties are called Custom Properties.**

Notice that it is referring to ***STIX Objects***, which could be interpreted as TLOs - not sub types and extensions.

**Comment by jordan2175** [comment]
Talked about this on 2020-02-11, we will talk about it again on our next working call.

**Comment by jordan2175** [comment]
Maybe on SCO, SDOs, SROs, Extensions, Sub-types, Main data types are all in question.  Also Granular markings.

**Comment by jordan2175** [comment]
Talked about this on the 2020-02-18 working call and we could get no consensus either way on what to do here.  The recommendation is to push this out to a future release to try and address.  The editors will, however, look at the text to see if we can make it more clear.  But the editors will error on the side of doing nothing, unless something simple can be done.

**Comment by jordan2175** [comment]
We added the following clause to the first paragraph of section 11.1. 

> and STIX Cyber Observable (SCO) Extensions

The whole sentence now reads as:

> There will be cases where certain information exchanges can be improved by adding properties to STIX Objects and STIX Cyber Observable (SCO) Extensions that are neither specified nor reserved in this specification; these properties are called Custom Properties.

This should address this issue, and stay within the spirit of the original design.

**Comment by jordan2175** [comment]
Rich P and I are closing this issue, if others feel this needs further work, please comment and reopen.
