### ISSUE TITLE
Should custom-extension names always end with "-ext"

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#216]
We always end the extension names explicitly in the spec with "-ext".  Should we add a MUST statement about naming custom extensions?

**Comment by jordan2175** [comment]
Talked about this on the 2020-01-28 working call.  Consensus on the call is to make this change.

**Comment by jordan2175** [comment]
Added the following text to 11.3.1 as bullet point 3:

> Custom Extension names MUST end with "-ext".
