### ISSUE TITLE
It is not possible to reliably determine if a custom object is an SDO/SRO or an SCO

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#217]
Custom Objects in STIX 2.1 could be a SDO/SRO or an SCO, but there is nothing in the spec that allows an implementation to determine which.  cti-python-stix allows users to "register" custom object, but other implementations might not, and unregistered custom objects are still an issue.

There are several "hints" that a custom object is an SCO - for instance, they may use a uuidv5 id, but nothing reliable.

No elegant easy solution comes to mind - but do we want to devise something for 2.1?

**Comment by varnerac** [comment]
See also: https://github.com/oasis-tcs/cti-stix2/issues/131

**Comment by jordan2175** [comment]
We should add this to section 11 as this is only needed for custom objects.  So if you get an object that  is not part of a defined / known stix object, then you could look at something like an "object_type" property to see if it was an sdo, sro, or sco.

**Comment by jordan2175** [comment]
We talked about this on 2020-02-11.  The consensus on the working call is to not do anything here.

**Comment by rpiazza** [comment]
@jordan2175 
I think this issue needs to be handled eventually - can you move to 2.2?
