### ISSUE TITLE
Is the constraint on SCO url's value too strict?

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#218]
The description for the value of a URL SCO is:

```
The value of this property MUST conform to [RFC3986], more specifically 
section 1.1.3 with reference to the definition for "Uniform Resource Locator".
```

This constraint would imply that the following URL SCO is invalid, since the "scheme" (e.g. http) is mandatory:

```
{
     "id": "url--7638df5b-415e-53ea-80eb-ee8507ea3616",
     "type": "url",
     "value": "hugesoft.org"
}
```

Is this constraint too restrictive?

**Comment by varnerac** [comment]
I think the restrictiveness is a good thing in this case. `http` vs `https` may have significance.

**Comment by jmgnc** [comment]
If we allow this, we need to be explicit about the defaults for the missing parts of the URL, ala https vs http...  if a person wants just a domain, they should be using a different object type.

I'd prefer that this NOT be allowed, as explicit is better than implicit, as it's more defaults that an implementation would have to hard code to implement the standard.

**Comment by rpiazza** [comment]
@jmgnc makes a great point - you should use a domain-name object in this case.  Do we need to add any text to the spec. or is that for the "best practices" document - if ever written...

**Comment by jordan2175** [comment]
Talked about this on the 2020-02-18 working call and Rich P decided that this was no longer an issue. Closing.
