### ISSUE TITLE
RFE: Classification proposal

### ISSUE THREAD

**Issue by JasonKeirstead** [oasis-tcs/cti-stix2#22]
RFE to implement the Classification proposal as in the playground document. This proposal would allow threat intelligence vendors to indicate the "known good" as well as the bad.

Note, I do not care what the name is. I just can not come up with a good name.

https://docs.google.com/document/d/1wiG6RoNEFaE2lrblfgjpu3RTAJZOK2q0b5OxXCaCV14/edit#heading=h.snfvxw2o7p1u

**Comment by treyka** [comment]
This issue is superseded by #56.
