### ISSUE TITLE
Need to make representation of operating system consistent across objects

### ISSUE THREAD

**Issue by ppatrick-fireeye** [oasis-tcs/cti-stix2#220]
The Malware Analysis object represents the operating system used as a Software object, where as that same information is referenced in Malware and Course of Action as a string that contains a CPE/SWID etc.

We should make these consistent across the set of objects.

**Comment by jordan2175** [comment]
Rich P and I talked about this on an editors call and think we should try and do something here to make them consistent.  If we continue to reference `software` then we need to add SWID to the `software` SCO.  We should probably also have these have the same property names.  Need to pay attention to what the means of the two different property names are and what they could include and not include.

**Comment by ppatrick-fireeye** [comment]
I agree with the direction that you and Rich P are considering.  If we went down the path of always using a Software object, then we should definitely change the cpe property to something more like a dictionary where key could represent the naming authority and the value would be the identifier.  This would achieve a similar set of flexibility as that provided by using External References, which are not permitted on SCOs.

The additional advantage to using a Software object, is people can still specify what software (e.g., operating system) was used without having to know a valid CPE/SWID/etc.

**Comment by jordan2175** [comment]
This is similar to #160

**Comment by ikiril01** [comment]
I agree that this needs to be fixed, but I'd err on the side of just adding a new SWID property to the Software object instead of a more generic dictionary-based property. Unless we feel like there are other software identifiers that users would need (or if there are any new formats coming out), having two string-based properties makes it easier to parse and consume this data.

**Comment by jordan2175** [comment]
Talked about this on the 2020-02-18 working call and the consensus was to make this change.

**Comment by jordan2175** [comment]
changes made.
