### ISSUE TITLE
New SCO for container

### ISSUE THREAD

**Issue by ejratl** [oasis-tcs/cti-stix2#228]
I would like to be able to exchange information about containers via STIX. This is roughly possible using Software and Process objects, but that is not ideal. It would be nice to have a Container object to model container images and container instances.

Data models for Containers exist, see [ECS](https://github.com/elastic/ecs/blob/master/schemas/container.yml) and [Sysflow](https://sysflow.readthedocs.io/en/latest/spec.html) for examples.

I would like to propose the following data model for a container to start the discussion about adding the Container SCO to STIX at the next opportunity.

|  Property Name  |  Type  |  Description  |
| --- | --- | --- |
| type (required) | string | The value of this property MUST be container. |
| container_name (optional) | string | The human readable name of the container. |
| is_privileged (optional) | boolean | Specifies whether the container instance is running as a privileged container. |
| image_name (required) | string | The name of the container image. |
| container_type (required) | open_vocab | Specifies the type of the container. This is an open vocabulary and values SHOULD come from the container-type-ov open vocabulary. |
| state (optional) | open_vocab | Specifies the observed state of the container instance. This is an embedded open vocabulary and values SHOULD be one of created, modified, reup |

--- 
## Container Type Vocabulary
Vocabulary Name: container-type-ov

The container type vocabulary is currently used in the following SCOs:
Container

An open vocabulary of Container types.

### Vocabulary Summary
docker, mesos, lxc, libvirt_lxc, rkt, oci, custom

 Vocabulary  Value | Description
 --- | ---
docker | Specifies a Docker container.
mesos | Specifies a mesos container.
lxc | Specifies an LXC container.
libvirt_lxc | Specifies a libvirt LXC container.
rkt | Specifies a rkt container.
oci | Specifies an oci standards based container.
custom | Specifies a custom container type.

**Comment by jordan2175** [comment]
This should be done in the next version of STIX or via an extension.

**Comment by allant0** [comment]
Agree on next release or extension/

**Comment by srrelitz2** [comment]
Recommend for new Extension
