### ISSUE TITLE
Clarity is needed in section 2.9, concerning creating a deterministic id

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#230]
Here is a STIX object:

```{
  "type": "network-traffic",
  "spec_version": "2.1",
  "id": "network-traffic--630d7bb1-0bbc-53a6-a6d4-f3c2d35c2734",
  "src_ref": "ipv4-addr--e42c19c8-f9fe-5ae9-9fc8-22c398f78fb",
  "dst_ref": "ipv4-addr--03b708d9-7761-5523-ab75-5ea096294a68",
  "protocols": [
    "ipv4",
    "tcp"
  ],
  "src_byte_count": 147600,
  "src_packets": 100,
  "ipfix": {
    "minimumIpTotalLength": 32,
    "maximumIpTotalLength": 2556
  }
}
```

The way I understand JCS, the string to canonicalize, based on the contributing ids would be:

	'{"dst_ref":"ipv4-addr--03b708d9-7761-5523-ab75-5ea096294a68","protocols":["ipv4","tcp"],"src_ref":"ipv4-addr--e42c19c8-f9fe-5ae9-9fc8-22c398f78fb"}'

However, the spec is somewhat ambiguous about what should be canonicalized:

> The value of the name portion SHOULD be the list of "ID Contributing Properties" defined on each SCO and those properties SHOULD be stringified according to [JCS] to ensure a canonical representation of the JSON data.

"list of" could be (and was in python-stix2) construed as _just_ the property values.

Some discussion from Andy Chisholm <chisholm@mitre.org> (bolded by me):

It seems to me, the STIX spec decides *what* to canonicalize, i.e. what
sort of data structure.  JCS tells us *how* to canonicalize.  The second
part does not influence the first, it's the other way around.  So it
doesn't make sense to say we're using objects instead of lists because
of something JCS says (something that didn't really make sense to me
from this morning's meeting).  What we canonicalize is our sole
discretion.  If we choose objects, then it makes sense that JCS imposes
requirements on how property names of objects are JSON-serialized, not
just the values.  But we don't have to choose objects (at the top
level... list values could of course be objects).

Anyway, yeah like I said in the email Chris forwarded, the STIX spec's
description of how to create UUIDv5's is not very good. **It doesn't say
property "values", but it does say "list", and it doesn't make much
sense to put only the names into a list.  If it had meant list of
name-value pairs (e.g. as length-2 arrays), it seems like it would have
said that.  The most plausible meaning to me, was that it meant property
values.**  That does have the drawback that if the same values occurred in
the same order for different property names of different object types,
you'd wind up with the same UUID.  On the other hand, adding property
names doesn't completely fix that problem: two different object types
could have the same property names and values in the same order as
contributing properties.  Then objects of two different types would get
the same UUID.  "type" isn't an ID contributing property for any SCOs,
from what I saw.  So perhaps adding names makes it more unlikely to have
UUID collisions, but it's not impossible.  I think you'd have to add
"type" as an ID contributing property to guarantee unique UUIDs across
types.

Yes, UUIDv5's have both names and namespaces, but we treat the namespace
as fixed and spec-prescribed [1], so this discussion is only about
names.  The JSON isn't the "name", but it directly determines the name.
So it is what we need clarity on.

**Comment by jordan2175** [comment]
We talked about this on an editors call and need more information on what needs to be fixed or changed.

**Comment by rpiazza** [comment]
This was changed in python-stix2 - see https://github.com/oasis-open/cti-python-stix2/pull/402.

I reviewed this with the MITRE dev team - it should explicitly say to use the property-name/value pair. See my first comment above.

Current
> The value of the name portion SHOULD be the list of "ID Contributing Properties" defined on each SCO and those properties SHOULD be stringified according to [RFC8785] to ensure a canonical representation of the JSON data.

Proposed
>The value of the name portion SHOULD be the list of "ID Contributing Properties" (property-name and property value pairs) defined on each SCO and those properties SHOULD be stringified according to [RFC8785] to ensure a canonical representation of the JSON data.

**Comment by jordan2175** [comment]
JMG is going to propose better text.

**Comment by jordan2175** [comment]
We talked about this again today and JMG will have something by next week's call, if not, we will move forward with the MITRE proposed changes.

**Comment by jmgnc** [comment]
Minor changes to the proposed text:
> The value of the name portion SHOULD be the list of "ID Contributing Properties" (property-name and property value pairs) as an object, and the object be serialized according to [RFC8785] to ensure a canonical representation of the JSON data.

**Comment by jordan2175** [comment]
We will tweak slights, to make sure that we include the text about where the ID contributing properties are coming from and that it is a JSON object. 

> The value of the name portion SHOULD be the list of "ID Contributing Properties" (property-name and property value pairs) as defined on each SCO object and be represented as a JSON object that is then serialized / stringified according to [RFC8785] to ensure a canonical representation of the JSON data.
