### ISSUE TITLE
Protocol normative statement seems to be contradictory

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#231]
> Protocols MUST be listed in low to high order, from outer to inner in terms of packet encapsulation. That is, the protocols in the outer level of the packet, such as IP, MUST be listed first.

Here are two different interpretations:

 \# 1 
[
    "ipv4" - layer 3
    "tcp" - layer 4
    "smtp" - layer 7
]
 
\# 2

[
    "smtp" - layer 7
    "tcp" - layer 4
    "ipv4" - layer 3
]

"listed in low to high order" seems to imply # 1, but "from outer to inner in terms of packet encapsulation" seems to imply # 2.

**Comment by jordan2175** [comment]
We talked about this on an editors call and Rich says we can reject it.
