### ISSUE TITLE
Ambiguity about Stix Bundles & custom properties

### ISSUE THREAD

**Issue by emmekappa86** [oasis-tcs/cti-stix2#233]
Reading the specs, the use of custom properties in a STIX Bundle might seem forbidden. This comes from the fact that: 

- custom properties apply to STIX Objects (Section 11 and Section 11.1)
- Stix Bundles are not STIX Objects (Section 8)

Nevertheless, Section 8 states "A Bundle is transient, and implementations SHOULD NOT assume that other implementations will treat it as a persistent object or keep any custom properties found on the bundle itself."

I believe this last paragraph tells the true as the specs do not actually provide any real restriction to the use of custom properties.

**Comment by rpiazza** [comment]
You have made the correct inference.  Bundles cannot have custom properties.  The spec language should be less ambiguous.

**Comment by emmekappa86** [comment]
I have actually raised this point because I had a use case in which I wanted to take advantage of custom properties in the Bundle. In this use case, I have several components that create STIX 2.1 data and the same information might be represented in slightly different ways or might need specific modifications later on in my pipeline. The use of custom properties in the Bundle would have allowed me to quickly identify who created the Bundle and what modifications to apply later on. I guess, the alternative would be creating a custom object for that but I am not sure I understand the reason why the use of custom properties in the Bundle should make STIX 2.1 data explicitly invalid.

**Comment by rpiazza** [comment]
I would tend to agree with you.  I can only say that this was explicitly discussed in the specification technical committee meetings, and that was the decision made by the committee.  I encourage you to join the committee (see https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cti) to make your opinions heard.  There is also a mailing list (cti-comment - search for that text on that page) for non-members.

**Comment by emmekappa86** [comment]
Yep, I am Marco from Siemens and I am the committee :) I probably missed that discussion

**Comment by rpiazza** [comment]
Reopened to be considered by the CTI spec editors

**Comment by jordan2175** [comment]
STIX 2.1 now supports extensions and custom properties are deprecated. However, there is nothing in the spec that I am aware of that prevents you from using custom properties on a bundle or extensions on a bundle. With that said the TC believes that Bundles should have NO semantic meaning and are only used as JSON wrappers for transmission. 

I believe what you are looking for is the STIX Grouping object. That would give you the context and meta-data and semantic meaning that I believe you are looking for.  We created the Grouping object to address the very issues you called out.
