### ISSUE TITLE
Must a Network Traffic object with the tcp extension have a protocol of tcp

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#236]
MUST the protocols property of a network traffic object that contains the tcp extension be only [ "tcp" ]
Are any other values allowed?

**Comment by jordan2175** [comment]
Need to talk about.

**Comment by jordan2175** [comment]
In the various network traffic extensions, we should add a normative statement that says something like:

> If this extension is used, then X value should be added to the protocols property on the network traffic object.

**Comment by jordan2175** [comment]
Added the following text to 6.12.1, the protocols property description.

> If the protocol extension is present, the corresponding protocol value for that extension SHOULD be listed in this property.

**Comment by jordan2175** [comment]
Also added this kind of text to each of the extensions:

> The corresponding protocol value for this extension is http.
