### ISSUE TITLE
Typo Fix: Extensions use of property-extension in Examples

### ISSUE THREAD

**Issue by emmanvg** [oasis-tcs/cti-stix2#238]
Based on version of the document: STIX v2.1 WD11 (CSD06) 2020-15-01

Some examples wrongfully use `"property_extension"` for the extension type. The value called for is `"property-extension"` (hyphen)

Occurs in:
- Section 7.3.2.2 - Example with ID "indicator--a932fcc6-e032-176c-126f-cb970a5a1ade"
- Section C.2.2 - Example with ID "indicator--e97bfccf-8970-4a3c-9cd1-5b5b97ed5d0c" and "artifact--6f437177-6e48-5cf8-9d9e-872a2bddd641"
- Section C.2.3 - Example with ID "sighting--ee20065d-2555-424f-ad9e-0f8428623c75"
- Section C2.4 - Example with ID "marking-definition--34098fce-860f-48ae-8e50-ebd3cc5e41da"
- Section C2.5 - Example with ID "language-content--0911f616-727f-48cb-a4c5-9420299562a4"

There is also an old use of `toplevel_property_extension` in Section 7.3.2.2 non-normative text before an example with ID "extension-definition--71736db5-10db-43d3-b0e3-65cf81601fe1". Suggest change to `toplevel-property-extension` if referring to extension type.

**Comment by jordan2175** [comment]
Talked about this on an editors call and these have been fixed in the master document. These are all fixes to examples.
