### ISSUE TITLE
Should the versioning of SCOs be revisited because custom properties are deprecated?

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#239]
Text from the spec:

> In STIX 2.1, SCOs do not explicitly have those three versioning properties. Therefore, a SCO cannot be versioned unless custom properties (discussed in section 11.1) are used. Producers who do this SHOULD use the property names created_by_ref, revoked, created, and modified.

A normative statement to use deprecated functionality seems wrong

**Comment by jordan2175** [comment]
This is talked about in section 3.6

Original Text

> In STIX 2.1, SCOs do not explicitly have those three versioning properties. Therefore, a SCO cannot be versioned unless custom properties (discussed in section 11.1) are used. Producers who do this SHOULD use the property names created_by_ref, revoked, created, and modified.

New Text

> In STIX 2.1, SCOs do not explicitly have those three versioning properties. Therefore, a SCO cannot be versioned unless extensions (discussed in section 7.3) are used. Producers who do this SHOULD use the property names created_by_ref, revoked, created, and modified.
