### ISSUE TITLE
Integration of system or network status

### ISSUE THREAD

**Issue by lizitong67** [oasis-tcs/cti-stix2#245]
How can I integrate the system or network statuses, such as system logs and network traffics, so I can perform the attack detection with the help of the CTI.

**Comment by jmgnc** [comment]
Hello,

Note: there are various systems/software packages out there that will do each of these steps, but we cannot recommend one over the other.  There is the STIX 2 Preferred (https://oasis-stixpreferred.org/) program that software vendors can use to verify that their products are STIX 2 compliant.  The interop specification defines various Personas (https://docs.oasis-open.org/cti/stix-taxii-2-interop-p1/v1.1/cn01/stix-taxii-2-interop-p1-v1.1-cn01.html#_Toc532826856 ) which can help understand what software is used for each step of the process.

The first step of the process it to use software to encode the system logs and network traffic into STIX Observed Data objects.  Once you have the data, then Indicator Objects can be used/written to match against the STIX Observed Data objects for attack detection.  There are various feeds that provide some Indicators, but likely you'll need to look at the Indicators to decide if and how to apply them to the network.

Hope this helps!
