### ISSUE TITLE
Change the name of STIX Helper Objects to STIX Meta Objects

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#246]
A request from Marlon Taylor

**Comment by marlontaylor** [comment]
Recommendation: Change “**STIX Helper Objects**” to “**STIX Meta Objects**”

**STIX Helper Objects** is only mentioned once in the specification, in the table at the bottom on _section 3.2_, and overlaps in meaning with **STIX Meta Objects** which is used throughout the rest of the specification.

**Comment by jordan2175** [comment]
This is an editorial issue and we will fix in the master document.
