### ISSUE TITLE
Fix extensions examples

### ISSUE THREAD

**Issue by clenk** [oasis-tcs/cti-stix2#248]
[for CS02; previously sent to cti-comments]

### Section 7.3.2:
*	Example - Create a new object type:
	-	Both objects' id properties should use UUIDv4 since that is what the spec recommends - they currently use v1 and a variant reserved for backwards compatibility rather than RFC 4122.
*	Example - Adding properties to an existing STIX object instance:
	-	Add the required "pattern_type" property.
*	Adding properties at the top-level to an existing STIX object instance:
	-	Add "Example - " to this header to be consistent with the other examples here.
	-	Remove the comma at the end of the following line:
		*	"extension_type": "toplevel-property-extension",
*	Example - Adding two new STIX objects and properties to an existing STIX object instance:
	-	The indicator, my-favorite-sdo and extension definition object's id properties should use UUIDv4 since that is what the spec recommends - they currently use v1 and a variant reserved for backwards compatibility rather than RFC 4122.
	-	The extension definition object lacks created and modified properties.
	-	The extension definition object has a "created_by" property - this should be renamed to "created_by_ref" and given a value containing an actual UUID, preferably UUIDv4.
		*	Remove the comma at the end of the following lines:
			-	"extension_type": "new-sdo",
			-	"extension_type": "new-sco",

### Appendix C:
*	C.1.2:
	-	"id": "relationship--7f5b1a34-c64b-4ad4-8a0f-1ebeffaa2d4" needs one more character at the end to make it a valid UUID.
*	C.2.1:
	-	In the extension definition object, swap the "extension_types" line and "object_marking_refs" line so that the last line in the object doesn't have a comma and the properties match the order in the "Optional Common Properties" tables elsewhere in the spec.
	-	In the "my-favorite-sdo" object, remove the comma at the end of the "extension_type" line.
	-	The "my-favorite-sdo" object's id property should use UUIDv4 since that is what the spec recommends - it currently uses v1 and a variant reserved for backwards compatibility rather than RFC 4122.
*	C.2.2:
	-	The Indicator object needs a "pattern_type" property.
	-	The artifact object needs a comma after the "decryption_key" line.
*	C.2.3:
	-	The sighting object needs a comma after the "sighting_of_ref" line.
*	C.2.4:
	-	The marking definition has the same id as the spec-defined TLP Green marking definition, so it needs a different UUID.
*	C.2.5:
	-	In the language-content object, add a comma on the line above "extensions".
	-	In the language-content object, the extension-definition--... entry needs a closing "}".

**Comment by jordan2175** [comment]
Changes to 7.2.3 have been made in the master document.  All of the changes to appendix C have been made.
