### ISSUE TITLE
Make service_name Optional in windows-service-ext

### ISSUE THREAD

**Issue by ikiril01** [oasis-tcs/cti-stix2#25]
The `service_name` property in the Windows Service Extension of the Process Object (Part 4, §2.13.3) is currently required. To support additional use cases, such as capturing malware configuration parameters (without the service name), we should make it optional.

**Comment by gtback** [comment]
Is there an example of how this would be used? When would you observe a service but not be able to capture its name?

**Comment by ikiril01** [comment]
This one came out of MWCP - they can capture configuration parameters like service description or display name without a corresponding service name:

https://github.com/Defense-Cyber-Crime-Center/DC3-MWCP/blob/master/mwcp/resources/fields.json#L242-L273

**Comment by gtback** [comment]
I think "malware configuration parameters" aligns more closely with patterns than observed data. With patterns, you can specify just the fields you are interested in, not worrying about what is required.

**Comment by ikiril01** [comment]
Malware configuration parameters are found through static analysis and contain information that is useful for sharing via STIX. IMO, if we're going to capturing other forms of analysis data as observed data and not patterns (e.g., sandbox outputs), it makes sense to capture configuration parameters in the same way.

**Comment by gtback** [comment]
My point was that if you observe configuration parameters via a config file, that's different from observing the thing itself (as in a sandbox). Just like saying "if you observe something ..." (an indicator) is different from actually observing the thing.

**Comment by gtback** [comment]
I talked to @ikiril01 about this, and realized I had forgotten that you can use Cyber Observable objects outside of the Observed Data SDO. I agree that it makes sense to use Cyber Observable objects for capturing this data. 

I wonder if there's a good way to say that certain fields are required in Observed Data, but optional in other use cases, like these malware configuration parameters.

**Comment by ikiril01** [comment]
This would be backwards breaking, so we need to discuss the pros and cons.

**Comment by jordan2175** [comment]
This was done back in working draft 01 and just never closed.
