### ISSUE TITLE
Sighting.sighting_of_ref refers to now-deprecated Custom Objects

### ISSUE THREAD

**Issue by clenk** [oasis-tcs/cti-stix2#251]
[for CS02; previously sent to cti-comments]

The description of "sighting_of_ref" says it "MUST reference only an SDO or a Custom Object." Does this need to be updated to account for extensions?

For example, we might remove the text "or a Custom Object" given the assumption that the term "SDO" includes the SDOs defined in the spec, custom SDOs defined using the now deprecated custom object type mechanism, and custom SDOs defined using a "new-sdo" extension.

**Comment by jordan2175** [comment]
In 5.2 we changed the text from:

> This property MUST reference only an SDO or a Custom Object.

to

> This property MUST reference only an SDO.

Just removed the custom object.
