### ISSUE TITLE
Add abbreviation of "STIX Meta Objects" as "SMOs"

### ISSUE THREAD

**Issue by marlontaylor** [oasis-tcs/cti-stix2#252]
Recommendation: Add abbreviation of "**STIX Meta Objects**" as "**SMO**" and "**SMOs**" as appropriate

**STIX Meta Objects** is used in the specification along side the categories but does not have an abbreviation like the others such as SDOs, SCOs, and SROs. **SMOs** as an abbreviation would be consistent with the rest of the object types and the specification style.

**Comment by jordan2175** [comment]
Changes made in master document.

**Comment by clenk** [comment]
Does the last sentence of the second paragraph of the Grouping description in section 4.4 need to be changed as well?
> The Grouping SDO contains a list of references to SDOs, SCOs, and SROs
to
> The Grouping SDO contains a list of references to SDOs, SCOs, SROs, and SMOs

grouping.object_refs just says "STIX Objects"

**Comment by rpiazza** [comment]
This sounds like an easy editorial change

**Comment by jordan2175** [comment]
Change made to 4.4. Closing.
