### ISSUE TITLE
Make the name property optional on the ​Windows Registry Value Type

### ISSUE THREAD

**Issue by treyka** [oasis-tcs/cti-stix2#26]
The `name` property on the Windows Registry Value Type (Part 3, §​2.17.2) is currently required. In order to support additional use cases, such as capturing malware configuration parameters, we should make it optional.

**Comment by gtback** [comment]
Is there an example of how this would be used?

**Comment by ikiril01** [comment]
This came out of MWCP - they can capture registry value data without the corresponding name: https://github.com/Defense-Cyber-Crime-Center/DC3-MWCP/blob/master/mwcp/resources/fields.json#L192-L199

**Comment by gtback** [comment]
As with #25, I think "malware configuration parameters" aligns more closely with patterns than observed data. With patterns, you can specify just the fields you are interested in, not worrying about what is required.

**Comment by gtback** [comment]
My [comment](https://github.com/oasis-tcs/cti-stix2/issues/25#issuecomment-333546788) on #25 applies here as well.

> I talked to @ikiril01 about this, and realized I had forgotten that you can use Cyber Observable objects outside of the Observed Data SDO. I agree that it makes sense to use Cyber Observable objects for capturing this data.
> 
> I wonder if there's a good way to say that certain fields are required in Observed Data, but optional in other use cases, like these malware configuration parameters.

**Comment by treyka** [comment]
We need to discuss the pros and cons since this would be backward-breaking. If we don't do this, it has implications for how the MWCP-inspired bits of Malware are currently defined in 2.1, Part 2.

**Comment by jordan2175** [comment]
This was done back in working draft 01 and just never closed.
