### ISSUE TITLE
Normative language for SCO versioning

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-stix2#260]
The spec says in 3.6:
 
In STIX 2.1, SCOs do not explicitly have those three versioning properties. Therefore, a SCO cannot be versioned unless extensions are used as discussed in section 7.3. Producers who do this SHOULD use the property names created_by_ref, created, modified, and revoked.
 
This seems to say you can’t do it with custom_properties, although it is not a normative statement.  Also should the SHOULD be a MUST?

**Comment by allant0** [comment]
The whole point of SCO having deterministic IDs (in most cases) and why we don't mandate versioning is that they don't change. If someone wants to treat a SCO like an SDO they can but that's not all use cases nor should be. If people want to extend an SCO then how will that work in the case where someone else creates the same SCO *without* those custom properties? This sounds like the person doing this is treating a SCO like an SDO and therefore cannot expect interoperability with that extension in all cases.

**Comment by jordan2175** [comment]
This was resolved by issued 239
