### ISSUE TITLE
add additional properties/relationships to Incident

### ISSUE THREAD

**Issue by jmgnc** [oasis-tcs/cti-stix2#264]
Propose to add the properties:
started (option): timestamp : The time at which this incident started.
ended (option): timestamp : The time at which this incident ended/resolved.

Also, suggest to add a suggected/recommended SRO:
occurred-at -> Location: to describe the location where the incident happened.

**Comment by allant0** [comment]
This is exactly why we should never have added incident in the 1st place. Its a slippery slope and won't end. Do it in a future release. Or better still propose an extension that defines what a group of vendors find useful in an incident and then add it as an extension that can be shared across vendors who agree on that definition of incident. This strategy would go a long way to solving the constant disagreement on what an incident represents in the 1st place. So I would argue we shouldn't add any further properties to incident regardless and show people that the best way to do this is via extensions.

**Comment by srrelitz2** [comment]
OBE with STIX extensions.
