### ISSUE TITLE
Proposal to add additional terms to infrastructure-type-ov vocab

### ISSUE THREAD

**Issue by jmgnc** [oasis-tcs/cti-stix2#266]
Defender infrastructure is not represented in the infrastructure-type-ov vocab, I propose to following additions:
firewall -- Device that inspects network traffic, and restricts is based upon defined policies
workstation -- (another name would be good) General machine used for work by an organization that needs protection.
infrastructure -- routers/switches
control-system -- such as IoT, HMI, RTU, PLC or other ICS devices.

**Comment by jordan2175** [comment]
We could make this if everyone agrees

**Comment by jordan2175** [comment]
We talked about this on the call today and of the 10 people on the call, no one thought they would be material and everyone agreed to add them.

**Comment by jordan2175** [comment]
Changes were made per working call.
