### ISSUE TITLE
Make user_id optional in User Account Object

### ISSUE THREAD

**Issue by ikiril01** [oasis-tcs/cti-stix2#27]
Currently, the `user_id` property is required in the User Account Object (Part 4, §2.16). To support use cases such as capturing a password used by malware (embedded as a configuration parameter) without a corresponding user ID, we should consider making this property optional.

**Comment by gtback** [comment]
If a password used by malware doesn't correspond to a user account, is using the User Account object really appropriate?

**Comment by ikiril01** [comment]
@gtback that's a fair question. I what it comes down to for us, is: does it make more sense to redefine an existing object property for a special case (such as this), or is it better to re-use an object property even if the context of usage may be different than normal?

**Comment by jordan2175** [comment]
That is a great question.  Which is better.  Use an existing object that may not be a great match, or define a new object, or just use a string field for it

Bret

**Comment by treyka** [comment]
We need to discuss the pros and cons since this would be backward-breaking. If we don't do this, it has implications for how the MWCP-inspired bits of Malware are currently defined in 2.1, Part 2.
