### ISSUE TITLE
Add YARA/Snort/OpenIOC to pattern of indicator

### ISSUE THREAD

**Issue by cheolholee75** [oasis-tcs/cti-stix2#28]
Hi All,

"pattern" property of "indicator" could support STIX, YARA, Snort, OpenIOC, etc. with "pattern_lang" property in earlier draft version of STIX 2.0. 
But, current draft support only STIX.

I think the former is better because it can support more wide use cases, specifically, legacy(not STIX) but commonly used nowadays such as YARA, Snort, OpenIOC. 
They are almost "de facto" standard still now.
I hope STIX 2 should have comprehensiveness.

Let's re-think our earlier decision.

**Comment by JasonKeirstead** [comment]
I would alternatively like to propose supporting YARA, Snort, etc. *INSIDE* STIX Pattern comparison expressions opposed to having them seperate.

I would like to be able to do something like this

[ ip-address:value = '1.2.3.4' AND SNORT:'alert tcp any any -> any any (content:"ABC"; content:"DEF"; distance:1;) ]

**Comment by jordan2175** [comment]
I think this could be done in both places.  Add it to the indicator for now and then see about adding it to the pattern grammar in 2.2.  We probably need a way of tracking the version of the rule in addition to the rule itself.  A simple way of doing this IMHO is to create an additional property called "other_patterns" and have it be a subtype.  The subtype would have three properties a type that is tied to an OV, a version property, and the actual pattern.

**Comment by JasonKeirstead** [comment]
I do not actually support adding it to the indicator as it creates confusion & conflict of interest WRT supporting of STIX SCO if indicators start being sent with many other languages. It also creates a huge interoperability challenge for implementors. Its a very large can of worms. Adding it to the grammar is a lot simpler and avoids many of these issues.

**Comment by jordan2175** [comment]
We talked about this on the 2019-06-11 working call. We decided to add pattern_type and pattern_version properties.  The open-vocab would contain snort and yara at a minimum.  We may need to make sure a relationship exists to say that two are semantic equivalent.   STIX Preferred will mandate that STIX patterning is required.

**Comment by jordan2175** [comment]
Text added to the document.  please review.
