### ISSUE TITLE
Implementation of new Observables / Observable Extensions

### ISSUE THREAD

**Issue by securitiz** [oasis-tcs/cti-stix2#282]
I'd like to (re)introduce the idea of adding several types of observables, some of which have already been brought up in other issues (#46 , #45 )

- ISP
  - technically an organization, any way to distinguish Org vs ISP in relation to an IP? maybe a boolean property
- Windows Scheduled Task
- [Windows Events](https://docs.microsoft.com/en-us/windows/win32/sync/interprocess-synchronization)
- [Windows File Mapping](https://docs.microsoft.com/en-us/windows/win32/memory/file-mapping)
- Windows Pipe
- Windows Class
- Windows Window Name

Have any of these been discussed and shot down? If so, can someone point me to the reasoning and proposed workaround?

**Comment by rpiazza** [comment]
Hi @securitiz,

Thanks for the issue, but it is probably more appropriate for the STIX specification issue tracker (https://github.com/oasis-tcs/cti-stix2).  Please refile it there or comment on #45 and #46.

On the other hand, you could use the extension facility (see spec section 7.3) to implement these as "new-sco"s.
