### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#3]
The development of capabilities in STIX to capture the location of STIX Objects.

**Work area:**
- [John's Proposal](https://docs.google.com/document/d/1SrwLhO-glQ9dnkj3BYfSd9ITr_L7Ai_JEnn1tqEO_dg/edit)
- Allan's Proposal: See slack channel

**Slack:** #location

## Scope
Any capabilities necessary to represent location information for STIX objects.

## Examples
* A threat actor targets victims in some geographic area
* A sighting was seen by an organization from some geographic area
* An information source is from some area or has some address
* A threat actor is located in some area
* Malware originated from some area
* Usage in cyber observables (TBD)

## Open Questions
* [x] Separate SDO (Allan's proposal) or field on other SDOs (John's proposal)
* [x] Format to use for geolocation (lat/lng/radius/etc)
* [x] Format to use to capture civic address information

**Comment by johnwunder** [comment]
A series of working calls and e-mail addresses has led to the following consensus:
- A separate SDO (Allan's proposal)
- No GeoJSON
- A simple set of fields, similar to MaxMind, for civic addresses plus lat/long for geolocation.

**Comment by jordan2175** [comment]
Added to the main 2.1 documents.
