### ISSUE TITLE
Expand Encryption Algorithm Vocabulary

### ISSUE THREAD

**Issue by ikiril01** [oasis-tcs/cti-stix2#30]
It has been pointed out that our current encryption-algo-ov is missing some key values, so we should consider expanding it with the following (as a minimum):

AES-192, AES-256, RC4, RC5, RC6

**Comment by ikiril01** [comment]
This needs further discussion to ensure that we make the values in this vocabulary useful for practical CTI use cases.

**Comment by jordan2175** [comment]
Can you look at this and add suggestions as needed?

**Comment by jordan2175** [comment]
We talked about this on 2019-06-04 and decided to move to STIX 2.2

**Comment by rpiazza** [comment]
Because this is an open-vocab, I think we can leave this for 2.1+
