### ISSUE TITLE
Dictionary keys in the hashes property on the File Object MUST come from the hash-algorithm-ov

### ISSUE THREAD

**Issue by treyka** [oasis-tcs/cti-stix2#32]
Dictionary keys in the `hashes` property on the File Object **MUST** come from the `hash-algorithm-ov`. Clarifying text added to 2.1, Part 4 in suggestion mode.

**Comment by JasonKeirstead** [comment]
Why can't this be a MUST ?

**Comment by treyka** [comment]
@JasonKeirstead I'm fine with **MUST**. Just updated the issue description accordingly.

**Comment by treyka** [comment]
TODO: review specs and ensure that all references to `hash-algorithm-ov` are consistent (**SHOULD** => **MUST**)

**Comment by gtback** [comment]
I'm :+1: for **MUST**

**Comment by jordan2175** [comment]
I am for a MUST and I really wonder if we should have a separate more minimal list of hash vocabs for things in STIX that use it, rather than a vocab for talking about how something was done. I am namely thinking of the use of this vocab on the hashes property for the external references.

**Comment by jordan2175** [comment]
Added a suggestion for this to section 6.1.1, 6.7.3.2.1, 6.7.6.2.1, 6.7.6.3.1, 6.18.1, 6.7.6.1, 

It was already on 6.7.1

Please review to make sure that is right.

**Comment by clenk** [comment]
Should this be changed to a MUST in the definition for the hashes data type in section 2.7 as well?

**Comment by jordan2175** [comment]
@clenk please add a suggestion in the document for that.

**Comment by jordan2175** [comment]
Change from clenk was accepted.
