### ISSUE TITLE
Incorrect link to Patterning in "STIX Version 2.1 - Part 2 - WD01"

### ISSUE THREAD

**Issue by philroyer-phantom** [oasis-tcs/cti-stix2#33]
I think I am looking at an incorrect link in table 2.5.1 of "STIX Version 2.1 - Part 2 - WD01". This is the property table for the Indicator object. The link is called "STIX™ Version 2.0. Part 5: STIX Patterning" but it doesn't go to the Patterning specification like I think it should.

**Comment by philroyer-phantom** [comment]
I think the link target should be https://docs.google.com/document/d/12ZcuQWzNmPdpOJSNgvQFn59AgPAOorCW6ymQScxzdkM

**Comment by johnwunder** [comment]
Unfortunately this is correct, the way OASIS specs are written is that links to other parts (Part 5) of the same specification go to Additional artifacts. I wish we could do it the way you're suggesting, but for the official versions we can't.
