### ISSUE TITLE
Suggested Additions to industry-sector-ov

### ISSUE THREAD

**Issue by marlontaylor** [oasis-tcs/cti-stix2#34]
The following sectors are not mentioned in the industry-sector-ov:

- Chemical Sector
- Commercial Facilities Sector
- Dams Sector
- Nuclear Reactors, Materials, and Waste Sector
- Water and Wastewater Systems Sector

the term Sector could be omitted

**Comment by JasonKeirstead** [comment]
I support this RFE.

**Comment by marlontaylor** [comment]
Here's the list of DHS Critical Infrastructure Sectors: https://www.dhs.gov/critical-infrastructure-sectors

Is this going to be included in CSD01?

**Comment by johnwunder** [comment]
F2F:
- Some discussion of just wholesale using another list, like SIC codes or UN sectors
- @marlontaylor will respond specifically to @jordan2175's questions

**Comment by marlontaylor** [comment]
@johnwunder @jordan2175 and I spoke at the F2F and agreed to the inclusion of the items in this request. 

Depending on future change requests to the list the TC may reevaluate a different list but for now the consensus is to continue with the current list and with the addition of the terms within this request.

**Comment by jordan2175** [comment]
We should address this in working draft 05

**Comment by jordan2175** [comment]
I think if we do this, I would like t structure them somehow as more specific types of things we already have, similar to what we have done for the regions.

**Comment by jordan2175** [comment]
We talked about this on the 2019-06-11 working call.  @marlontaylor Can you add further clarification on this? Specifically address conflict issues with other values in the vocab that are similar.  Please do so by end of June 2019.

**Comment by ikiril01** [comment]
@jordan2175 can we still add this to STIX 2.1?

**Comment by jordan2175** [comment]
@ikiril01 the information I have is we are still waiting on Marlon to provide extra details.  The minutes from that meeting say we did not have consensus to add them and Marlon agreed to provide some extra details / rational.  But that was back from June 11th.

**Comment by marlontaylor** [comment]
hi @jordan2175 here's the [documentation for the 16 critical infrastructure sectors](https://www.dhs.gov/cisa/critical-infrastructure-sectorsl).

> whose assets, systems, and networks, whether physical or virtual, are considered so vital to the United States that their incapacitation or destruction would have a debilitating effect on security, national economic security, national public health or safety, or any combination thereof.

The request is to add the unique sectors not  represented in the current industry-sector-ov:
- Chemical Sector
- Commercial Facilities Sector
- Dams Sector
- Nuclear Reactors, Materials, and Waste Sector
- Water and Wastewater Systems Sector

**Comment by jordan2175** [comment]
What if we added these to the vocab, but stylistically added them as sub-elements so if you do not want this level of granularity, you can see what the "parent" category is.  I propose that we do the following. I have also broken them up into individual sections.  That way if someone wanted that extra details they could have it.  But I would also be fine with just `nuclear` and just `water` and not their sub-sub elements. @ikiril01 @marlontaylor would this work for you and DHS?  I think it gives you want you want, a way to map your list to the STIX list and back. 

- agriculture
- aerospace
- automotive
- `commercial`
- communications
- construction
- defence
- education
- energy
- `chemical`
- entertainment
- financial-services
- government-national
- government-regional
- government-local
- government-public-services
- healthcare
- hospitality-leisure
- infrastructure
  - `dams`
  - `nuclear`
    - `nuclear-reactors`
    - `nuclear-materials`
    - `nuclear-waste`
  - `water`
    - `waste-water`
- insurance
- manufacturing
- mining
- non-profit
- pharmaceuticals
- retail
- technology
- telecommunications
- transportation
- utilities

**Comment by jordan2175** [comment]
Or maybe Chemical is not under Energy.  And maybe we just do nuclear and water.  That might work?

**Comment by ejratl** [comment]
Emergency Services is also one of the 16 sectors and it isn't clear what it would map to on this list. It should probably be added.

**Comment by rmasuoka** [comment]
@jordan2175 Are we going to change "Defence" to "Defense?"

**Comment by jordan2175** [comment]
@rmasuoka yes.  We will change the spelling.

**Comment by ikiril01** [comment]
@jordan2175 I like the sub-element approach but I don't see all of the entries that @marlontaylor requested. Also, how would this work in terms of capturing it in the specification itself since everything is just part of a table? My concern there is potential for confusion/complexity that's passed onto the end user.

**Comment by rpiazza** [comment]
@ikiril01 - if you mean sub-sub-elements like Nuclear Reactors, Materials, and Waste Sector - the editors thought adding two sub-levels was too complicated a change to introduce at this point.  This is more like the regions-ov, which has been around for a while.  

As far as you other point, we might to add something like the following sentence, here and for the regions-ov:

For a sub-element vocabulary value (i.e., ....), the choice of the sub-element is sufficient to indicate the element also.

**Comment by jordan2175** [comment]
We talked about this on the working call on 2020-02-18.  The consensus on the call was to add these.

**Comment by jordan2175** [comment]
Values added.
