### ISSUE TITLE
Suggested change for Dictionary - Common Data Type

### ISSUE THREAD

**Issue by emmanvg** [oasis-tcs/cti-stix2#35]
While writing tests to support the [LanguageContent](https://docs.google.com/document/d/1ShNq4c3e1CkfANmD9O--mdZ5H0O_GLnjN28a_yrEaco/edit#heading=h.cfz5hcantmvx) object I found myself with a problem using the `contents` dictionary. I saw RFC5646 supports language tags longer than 2 characters, but the STIX specs mandate 3 or more for keys in a dictionary. The examples found in the document use language tags that are too short. Will this mean that producers need to provide a more specific language tag?

Affects: [Section 2.2 Dictionary](https://docs.google.com/document/d/1ShNq4c3e1CkfANmD9O--mdZ5H0O_GLnjN28a_yrEaco/edit#heading=h.f6e8afjdtrse)

Should there be an exception to this MUST requirement or remove the requirement completely?

**Comment by emmanvg** [comment]
![dictionary](https://user-images.githubusercontent.com/8574582/31821356-dbf11ee4-b572-11e7-9707-02cdf1e31d9f.png)

**Comment by JasonKeirstead** [comment]
I don't know the history behind that MUST requirement, but I'd suggest it simply be removed.

**Comment by jordan2175** [comment]
We talked about this on the working call on 2018-01-13 and the consensus on the call was to remove the phrase "MUST have a minimum length of 3 ASCII characters".  

The people that voted for this to be remove were: Bret Jordan, Trey Darley, Allan Thomson, Mark Davidson, Chris Ricard, Sean Barnum, Rich Struse, Paul Patrick

Abstain: Sarah Kelley

**Comment by skelley1** [comment]
Point of clarification, this issue was discussed on the working call on Feb 13, 2018, NOT January 13.

**Comment by treyka** [comment]
The call for objections ended COB 02 March with no objections received to the TC mailing list. The change has been made in suggesting mode in STIX 2.1, Part 1 with a comment noting that it closes this Github issue. QED, we are closing this issue.
