### ISSUE TITLE
Confidence scales are not clear

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#38]
The Admirality scale we used for the confidence mappings has an item called "(Not present)" for "Truth cannot be judged". The intent was that the property is omitted, but that isn't really clear.

Some of the other scales say "Not specified", which also isn't consistent. This isn't a normative change, just a clarification to text.

**Comment by treyka** [comment]
@johnwunder Please review the current 2.1, Part 1 text and if this issue has been resolved (as @skelley1 and I believe it has), please close this issue. Thanks!

**Comment by johnwunder** [comment]
It was not, but I just fixed it with an editorial change.

**Comment by johnwunder** [comment]
Note that this is a modification to issue #4 and so will not be included in the 2.1 changelog.
