### ISSUE TITLE
Add parent_directory_ref property to Directory Object

### ISSUE THREAD

**Issue by ikiril01** [oasis-tcs/cti-stix2#42]
We should add a new **parent_directory_ref** property to the Directory Object, for specifying the parent directory of a directory. We already have a very similar **parent_directory_ref** property on the File Object.

**Comment by gtback** [comment]
A File object does not have a `path` attribute, so there is no way to express where on the file system the file is located without **parent_directory_ref**. The Directory object already has a (required) `path` attribute, so adding this in would create multiple ways of representing the same information.

**Comment by ikiril01** [comment]
@gtback good point. We'd probably have to add a fair amount of normative text to try and disambiguate between `path` and `parent_directory_ref`, which is reminiscent of the old CybOX 2.x File Object (and not in a good way!). I agree that it would be better to not include `parent_directory_ref` on the Directory.

**Comment by treyka** [comment]
This would represent two different ways of doing the same thing and the benefits of adding this capability are outweighed by the cost of confusing implementers.
