### ISSUE TITLE
Clarify Property Definitions on Process Object

### ISSUE THREAD

**Issue by ikiril01** [oasis-tcs/cti-stix2#47]
Jason had some confusion with regards to the process image name vs filename vs command line on the Cyber Observable Process Object and when you'd use each, so we should try to clarify the descriptions of these properties as necessary.

**Comment by ikiril01** [comment]
So I think the biggest issue here is that the `name` property is duplicative with respect to `binary_ref.name` . Given that the "name" of a process tends to almost always be the filename of the binary, I would suggest that we deprecate `name`.

**Comment by ikiril01** [comment]
As far as `command_line`, I would suggest updating the description from the existing:

"Specifies the full command line used in executing the process, including the process name (depending on the operating system)."

To the updated version:

"Specifies the full command line used in executing the process, including the process name **(which may be specified individually via the binary_ref.name property) and any arguments.**"

**Comment by ikiril01** [comment]
FYI, this is what Osquery has for these properties:


name | TEXT | The process path or shorthand argv[0]
path | TEXT | Path to executed binary
cmdline | TEXT | Complete argv

**Comment by johnwunder** [comment]
I've had this same question, definitely agree with fixing this for 2.1.

**Comment by treyka** [comment]
There are plenty of cases where a process name doesn't align with the binary filepath. For example, in *nix, where you have one binary with a number of different executable symlinks pointing to it and the binary alters its behavior based on how it's called (i.e., argv[0].) Similarly, in Windows™ where you have a callable DLL (with a main() function) with symbolic links as in the previous example.

**Comment by ikiril01** [comment]
@treyka interesting. I ran an experiment on this on my MacBook, and it least in OS X it looks like the name of the symlink is captured in the command-line but not the name of the process.

```
ikirillov@foo-PC:~$ top
58548  iBooks     
``` 

```
ikirillov@foo-PC:~$ ps -p 58548
  PID TTY           TIME CMD
58548 ttys010    0:01.00 ./iBooks-foo
```

**Comment by ikiril01** [comment]
@jordan2175 it looks like we've already made these changes to the Process SCO (`name` has been deprecated, the description for `command_line` has been updated, etc.), so there's nothing else that needs to be done here.

**Comment by jordan2175** [comment]
Looks like this was done some time back.  Closing.
