### ISSUE TITLE
Opinion Object

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#5]
The Opinion object would allow information creators to assert their opinion about objects created by other producers.

**Work area:** https://docs.google.com/document/d/15qD9KBQcVcY4FlG9n_VGhqacaeiLlNcQ7zVEjc8I3b4/edit#heading=h.haeazu2sh3sq

## Scope
The opinion object will be scoped to only capture opinions about STIX Objects (not fields in objects).

## Examples
* Producer A expresses agreement (+1) to an indicator published by ISAC B
* Producer C expresses disagreement with a campaign characterization from ISAC D

## Open Questions
* [x] Should the Opinion object have a text description field?
* [x] What description does the Opinion need to differentiate from the Intel Note object? Or, should they be merged?
* [x] What scale does the object use?

**Comment by johnwunder** [comment]
After a ballot on whether there should be an optional description field (yes) and some discussion of an author property, this object is ready to be moved to the drafts.

**Comment by jordan2175** [comment]
This content has been moved to the official 2.1 documents.
