### ISSUE TITLE
STIX Patterning language needs a null constant or is_null() function

### ISSUE THREAD

**Issue by treyka** [oasis-tcs/cti-stix2#52]

**Comment by gtback** [comment]
Definitely related to #51, and my comment there applies here as well.

**Comment by ikiril01** [comment]
We also need a few examples of where it makes sense to match against null values.

**Comment by treyka** [comment]
* Testing for the nonexistence of a specific Windows registry key
* Testing for the nonexistence of a value with a list-based specific Windows registry key
* Testing for the nonexistence of a specific email header

**Comment by jordan2175** [comment]
We talked about this on 2019-06-05 and this should be pretty easy to do, and we should try and get this done for 2.1.  But it needs someone to do the work.

**Comment by jordan2175** [comment]
Ivan is going to propose some text in the document for this.

**Comment by ikiril01** [comment]
Text has been added to the Comparison Operators table.

**Comment by jmgnc** [comment]
@ikiril01 I don't see the text.  I'm likely looking at the wrong document.  Can you please include a link?  Thanks.

**Comment by jordan2175** [comment]
Text was added to 9.6.1

**Comment by jordan2175** [comment]
The final text that was added is:

```
EXISTS a

a MUST be an Object Path which specifies a single property that MUST exist on the Object specified by the Observation Expression in order for the Comparison Expression to evaluate to true.

For example, EXISTS windows-registry-key:values would evaluate to true on a registry key that contains a 'values' property (regardless of its contents). 
EXISTS windows-registry-key:values
```
