### ISSUE TITLE
Bundle does not require all objects to be same spec version

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-stix2#55]
The language in the STIX Bundle does not really require that all objects be in the same spec version only that the spec version be 2.0.  We probably need some normative text that says all objects in the bundle need to be off the same specification version.

**Comment by MarkDavidson** [comment]
I think all content in a single bundle should be the same STIX version, and I believe most implementations probably work this way already. I support clarifying this in STIX 2.x.

**Comment by rjsmitre** [comment]
Suggested way forward: 
1. clarify spec_version in Bundle to be the highest version object in the Bundle
2. add spec_version to each object as a required property as of 2.1 with normative text saying that if not present the spec_version should be interpreted as "2.0"

**Comment by jmgnc** [comment]
for 2. MUST not should.

**Comment by jmgnc** [comment]
we'd also need to add verbiage to handle version upgrades.. i.e. when the author changes from 2.1, that a future version must not be down graded.

**Comment by MarkDavidson** [comment]
Possible Solution: Add a mixed STIX version media type to STIX 2.1
Parameters:

1. spec_version is required on all STIX objects. If spec_version is absent (i.e., in STIX 2.0 objects), spec_version is interpreted as STIX 2.0
2. TAXII responses with a media type of `...stix+json; version=2.0` MUST contain a bundle with only STIX 2.0
3. TAXII responses with a media type of `...stix+json; version=2.1' MUST contain a bundle with only STIX 2.1
4. TAXII responses with a media type of `...stix+json; version=mixed` MAY contain a bundle with any STIX version
5. A mixed-stix-spec-version STIX bundle should contain spec_version="mixed; max=2.1"

**Comment by jordan2175** [comment]
There is an option question on how to do mixed

**Comment by johnwunder** [comment]
I don't like the idea of mixed version bundles. I think I'm missing the use case here. My strong preference is to explicitly state that a bundle can only contain objects of a single version.

**Comment by jmgnc** [comment]
I'm split on this.  Part of the issue is that we decided to try to make STIX such previous versions of STIX documents are readable and understandable by future versions.  This means that a STIX 2.1 should be able to handle a STIX 2.0 document w/o misunderstanding it.  If this is the case, then returning STIX 2.0 documents in a 2.1 bundle is safe.

Though there is some debates about making breaking changes to 2.1 which would render the above rule invalid.

**Comment by jordan2175** [comment]
IMHO, STIX 2.0 is an MVP release that got us going.  But I do not see STIX 2.0 as being the mass production release that everyone deploys.  Yes, some organizations, including my own, have started work on STIX 2.0.  But even if there are breaking changes, it will be easy to have those implemented.  STIX 2.0 is not yet deployed in every product in every network.  So lets realize that we have the one last chance to make sure we fix things right and make sure we do not introduce new breaking changes for a future release.  Lets make sure all new features are well vetted before hand.  

The one things that would be such a horrible solution is to know we have a breaking change and not make it now, but try and make it in 2.2 or 2.3.

**Comment by emmanvg** [comment]
I think that supporting mixed versions of bundles can be a hard task, especially on the implementation side of things. As the spec progresses and the possibility of making backwards braking changes increases taking care of edge cases can be a pain. My preference would be to contain objects of a single version inside a Bundle.

**Comment by ikiril01** [comment]
I also don't really understand the use cases for different versions of objects in a single bundle, and I wonder if this raises some potential semantic complications, especially in terms of relationships. That is, would we then have to state in the specification that certain relationships are only valid between certain versions of objects?

**Comment by johnwunder** [comment]
We discussed this on the Feb 27 Working Call and the consensus on the call was to remove `spec_version` from bundle and add `spec_version` to the object common properties as a required field. `spec_version` will be removed per a broader conversation about how to deal with deprecation and breaking changes in the specs.

The TAXII issue discussed above will be discussed in the context of TAXII.

Notes from the working call are here: https://www.oasis-open.org/committees/document.php?document_id=62614&wg_abbrev=cti
