### ISSUE TITLE
Intel Notes

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#6]
The Intel Note object would allow information sources to add intelligence notes to objects created both by themselves and by others. For example, a comment with more information could be added to an existing object.

**Work area:** https://docs.google.com/document/d/15qD9KBQcVcY4FlG9n_VGhqacaeiLlNcQ7zVEjc8I3b4/edit#heading=h.uovlit7natfj

## Scope
The intel note object will be scoped to only capture notes about STIX Objects (not fields in objects).

## Examples
* Producer A adds a note to an object published by Producer B
* Producer C adds a note to an object they published themselves

## Open Questions
* [x] Does there need to be a separate field to capture the author of an intel note? If so, what does the field look like?
* [x] How do you differentiate an intel note from an opinion? From a report?

**Comment by johnwunder** [comment]
Discussed on 3/28 working call:

Strong consensus: identity should be an identifier
Strong consensus: intel note is ready to be done

**Comment by jordan2175** [comment]
This was added to the official documents and the name was changed form intel-note to just note based on discussion with Allan and Jason and then public reviews on a working call and via the email list.
