### ISSUE TITLE
Tool and Malware need aliases

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-stix2#64]
The tool object and malware object need a property called aliases.  John Wunder mentioned that they have run in to this with their ATT$CK work

**Comment by skelley1** [comment]
Our team has requested this feature as well.

**Comment by johnwunder** [comment]
F2F:
- Rough consensus is that this should be added
- Concern about having multiple places to look (things in the name should be in the aliases)
- May need to consider making it a tuple of source:name
- Probably need guidance on when to use aliases vs. a relationship to another object

**Comment by jordan2175** [comment]
This was accepted.
