### ISSUE TITLE
Clarify granular markings without versioning

### ISSUE THREAD

**Issue by varnerac** [oasis-tcs/cti-stix2#76]
STIX 2.0:

> Every representation (each time the object version is serialized and shared) of a version of an object (identified by the object’s id and modified properties) MUST always have the same set of properties and the same values for each property. In order to change the value of any property, or to add or remove properties, the modified property MUST be updated with the time of the change to indicate a new version.

I don’t know to reconcile this requirement in the spec with Granular Markings + Selectors. I want to strip restricted data, as denoted by the markings and selectors, from a STIX object before I transmit. However, the requirement above doesn't allow me to do this.

How do we pass a subset of an object based on granular markings?

**Comment by johnwunder** [comment]
F2F:
- We have an extensive discussion, we didn't really come to consensus. If there's a specific change that you think we should make please write it up as a proposal that the TC can evaluate. In the meantime I'm going to close this.
