### ISSUE TITLE
Infrastructure object

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#8]
The Infrastructure object would capture information about adversary infrastructure, such as command and control servers, download sites, e-mail delivery, etc.

**Work area:** https://docs.google.com/document/d/15qD9KBQcVcY4FlG9n_VGhqacaeiLlNcQ7zVEjc8I3b4/edit#heading=h.maky5z1n51ds

## Scope
Still being determined.

## Examples
* C2 servers for a particular campaign
* E-mail delivery typically used by an intrusion set

## Open Questions
Still being determined.

**Comment by jordan2175** [comment]
Added to working draft 04
