### ISSUE TITLE
Add extension mechanism

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#84]
Per discussion at the face to face and the results of the process ballot, STIX 2.1 needs to support objects describing which "extensions" they implement. This includes:

* [ ] Text in the process document describing how extensions work
* [ ] Additions and/or changes to the STIX specification to describe extensions in the object model
* [ ] Additions and/or changes to Part 5: Patterning to describe extensions in patterning

**Comment by ejratl** [comment]
Extensions were added in STIX 2.1.
