### ISSUE TITLE
Remove 30 Character Limit SHOULD Restriction in Dictionary and Hashes Types in Part 1

### ISSUE THREAD

**Issue by ikiril01** [oasis-tcs/cti-stix2#88]
We should remove the restriction in the Dictionary and Hashes types which says that "keys SHOULD be no longer than 30 characters in length". If you're an organization with a longish domain name and wish to conform to the requirements for naming custom properties (e.g., "x_foo_org_property_name"), odds are that you'll run afoul of this requirement. Accordingly, we should just remove this SHOULD and keep the existing MUST in place which states that property names should be no longer than 256 characters.

**Comment by jordan2175** [comment]
This change has been made.
