### ISSUE TITLE
Enhanced malware capabilities

### ISSUE THREAD

**Issue by johnwunder** [oasis-tcs/cti-stix2#9]
Enhanced malware capabilities will create enhancements to STIX (new objects, new properties on existing objects) to capture more in-depth malware analysis information. The intent is to capture much or all of the information that is currently expressable in MAEC directly in STIX.

**Work area:** https://docs.google.com/document/d/15qD9KBQcVcY4FlG9n_VGhqacaeiLlNcQ7zVEjc8I3b4/edit#heading=h.s5l7katgbp09

## Scope
* High-level characterization of malware used primarily for threat intel
* Low-level characterization of malware behavior used for malware analysis (e.g. sandbox output)
* Malware instances
* Malware families

## Examples
* DarkEnergy (family)
* Poison Ivy Instance w/ Hash XYZ (instance)

## Open Questions
Still being determined.

**Comment by skelley1** [comment]
The malware object has been completed and has been moved to the 2.1 specification. This issue can now be closed.
