### ISSUE TITLE
STIX 2.0 and 2.1 Specs have inconsistency WRT custom objects in bundles

### ISSUE THREAD

**Issue by JasonKeirstead** [oasis-tcs/cti-stix2#91]
In section 8.2 of STIX 2,1, the example shows all custom objects being put in a bundle property called "custom_objects". However, this property is not defined in the spec ( see section 6, Bundle... it is not there ).

The same problem is in STIX 2.0

Based on the normative text I must assume custom_objects is *not* a valid bundle property, and they should be at the same level as other objects

**Comment by jordan2175** [comment]
This was fixed back in working draft 01 of STIX 2.1
