### ISSUE TITLE
Add complex Language Content example to STIX 2.1, Part 1, §4 "Language Content"

### ISSUE THREAD

**Issue by treyka** [oasis-tcs/cti-stix2#95]
This issue stems from @jordan2175's comment on this bit of text from the Properties table, "If the original property is a list, the corresponding location in the translation object must also be a list. Each item in this list recursively maps to the item at the same position in the list contained in the target object. The lists MUST have the same length."

04 July 2018, @jordan2175 noted, "We really need an example of this the object one below."

**Comment by rpiazza** [comment]
I added an example which has this kind of content.  However, because I don't speak any other languages - I need someone who can create translations - it doesn't have to be **de** and **fr**, but the second one should have no translation for "Steal credit cards".  See section 7.1 of the spec.

**Comment by jordan2175** [comment]
The translation has been added based on Google translate.
