### ISSUE TITLE
generalize name, aliases, description, url

### ISSUE THREAD

**Issue by VladimirAlexiev** [oasis-tcs/cti-stix2#96]
I think these should be moved to [Common Properties](http://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_Toc496709274): `name aliases description url`.
- `name aliases description` are generic properties that can apply to pretty much anything, right?
- How about `url`? I come from a semantic web background where I'm used that everything has a URL. 
  - Currently `report` doesn't have a URL: you can put several in `external_references`, but isn't it logical to assume that each report will have one main URL where it's available, and could have more alternative URLs?
  - A `tool` usually has a homepage (of that product, or the project that creates it), which is a URL.

**Comment by jmgnc** [comment]
URL is not on a single STIX 2.1 object, but external_references is already a common property, so I don't think this is needed.

**Comment by JasonKeirstead** [comment]
+1 that Aliases and Description should be on every SDO. Have a hard time coming up with an object you would not want them for.

**Comment by jordan2175** [comment]
Here are the current objects in STIX 2.1 and the ones that have name, description, and aliases. 

Attack-Pattern
	Name
	Description
Campaign
	Name
	Description
	Aliases
COA
	Name
	Description
Grouping
	Name
	Description
Identity
	Name
	Description
Indicator
	Name
	Description
Infrastructure
	Name
	Description
Intrusion Set
	Name
	Description
	Aliases
Location
	Description
Malware
	Name
	Description
	Aliases
Malware-Analysis
	<NONE>
Note
	<NONE>
Observed Data
	<NONE>
Opinion
	<NONE>
Report
	Name
	Description
Threat Actor
	Name 
	Description
	Aliases
Tool
	Name
	Description 
Vulnerability
	Name
	Description
Relationship 
	Description 
Sighting
	<NONE>
Marking Definition
	Name
Language Content
	<NONE>

**Comment by jmgnc** [comment]
> @jmgnc the problem is that all external_references are equal, there isn't a primary one.
> And in practical terms, most important things worth discussing nowadays have a Home Page.

Then we should maybe add a machine readable entry for external_references.  Each url DOES have a description, so a bit of info can be added there, maybe a open vocab like labels (or what used to be labels?).

**Comment by JasonKeirstead** [comment]
One can almost see the pattern here. We have the set of SDOs that contain the actual intelligence, and the set of SDOs that do not, but instead contain discrete instance state & metadata / STIX structure.  Any of the ones that contain the actual intelligence, should all have Description and Aliases. Out of that giant list @jordan2175 posted the only ones in it that don't deserve Description and Aliases are Note, Language Content, Observed Data, Malware-Analysis, Opinion.  All the others deserve it (except arguably Relationship and Sighting, which seem a bit off - it is weird that Relationship has description today.

In fact, o

It makes me wonder if we should separate these two SDO classes for better organization in the spec? A topic for future discussion.

**Comment by jordan2175** [comment]
I think that is a good idea @JasonKeirstead, what would you propose we call this other group of objects? In WD04 we tried to build a table to better explain the objects.  So now would be the time if wanted to make some more changes.  I have long held the view that some of these objects "feel" different and do not belong in the same bucket.

**Comment by JasonKeirstead** [comment]
@jordan2175 I don't have any strong suggestion but I think there are indeed different bucks. I worry a bit about the churn it would cause at this point to open up the debate of which go into what bucket.

**Comment by jordan2175** [comment]
Produce a list of actual changes

**Comment by jordan2175** [comment]
We talked about this on the working call on 2019-06-11 and decided we would add aliases to attack-pattern and infrastructure and any other changes if required we would punt to 2.2.

**Comment by jordan2175** [comment]
Changes have been proposed in the document.
