### ISSUE TITLE
enable shared external_references

### ISSUE THREAD

**Issue by VladimirAlexiev** [oasis-tcs/cti-stix2#97]
`external_references` are not objects in STIX, as they have no identity.

But actual MITRE STIX data shows that references are reused **heavily** between objects. Eg a webpage describing an attack by a malware will be attached to the attack, the malware, and the relation between them.
See https://github.com/mitre/cti/issues/28 for a detailed analysis. Some references are reused **37 times** between objects.

I also think that external references are very similar to `reports`. The only difference is a matter of degrees:
- a report is supposed to include security analysis (eg the Wikipedia page about FTP does not)
- a report is supposed to be substantial (whereas a reference could be just one paragraph)

Note: `report` currently doesn't have `url` (see #96) and external ID (but IMHO some reports are known by such IDs).

**Comment by jordan2175** [comment]
They are currently embedded types just like kill chain.  I will leave this open, but am tagging it for a later release.

**Comment by jordan2175** [comment]
This is similar to #163

**Comment by ejratl** [comment]
The complications that this proposal would add provide an unclear benefit, especially since external references are rarely updated. Closing this for now, if you have a strong need for this, please reopen and provide a proposal.
