### ISSUE TITLE
Add type "system" to identity-classs-ov

### ISSUE THREAD

**Issue by JasonKeirstead** [oasis-tcs/cti-stix2#98]
identity-class-ov has no entry for "system" to describe the identities of machines. 

Suggest one be added with a description along the lines of "A logical system, or logical grouping of systems, to whom one would like to be able to trace origin of the STIX data to."

**Comment by jordan2175** [comment]
Rich P added this to the vocab.  Marking as done.

**Comment by delliott90** [comment]
Should the change be showing up here?
https://github.com/oasis-open/cti-stix2-json-schemas/blob/stix2.1/schemas/sdos/identity.json
